/**
 * Compliance Gap Analysis — UC-GAP-001 (THE-307)
 *
 * Answers the auditor question "what is still missing?" on top of the
 * ComplianceRequirement entities generated by UC-REQGEN-001:
 *   - per regulation:  which requirements are still open, KPI "5 of 9 open"
 *   - per element:     which open requirements hang on element X
 *   - global:          which elements carry the most open MUST requirements
 *
 * Design constraint (THE-389): every number here is computed LIVE from the
 * ComplianceRequirement collection on each request — never from cached
 * pipeline stats. A wrong number in front of an auditor is worse than a
 * slower request.
 *
 * A "gap" is a requirement whose status is open or in_progress. done means
 * fulfilled; waived means deliberately closed with a decision — neither is
 * outstanding work.
 */
import mongoose from 'mongoose';
import { buildRegulationKey } from '@thearchitect/shared';
import type { ConsumedRef } from '@thearchitect/shared';
import { ComplianceRequirement } from '../models/ComplianceRequirement';
import { Regulation } from '../models/Regulation';
import { getPipelineNorm } from './norm.service';
import { recordContextTrace } from './contextTrace.service';
import { computeVersionHash } from '../utils/regulationVersion';

export interface GapFilters {
  regulationId?: string;
  elementId?: string;
  priority?: 'must' | 'should' | 'may';
}

export interface GapItem {
  _id: string;
  regulationId: string;
  regulationTitle: string;
  title: string;
  description: string;
  priority: 'must' | 'should' | 'may';
  status: 'open' | 'in_progress' | 'done' | 'waived';
  linkedElementIds: string[];
  ageDays: number;
  createdBy: string;
  createdAt: Date;
}

export interface RegulationGapSummary {
  regulationId: string;
  regulationTitle: string;
  total: number;
  open: number;        // open + in_progress
  done: number;        // done + waived
  openMust: number;
  pctOpen: number;     // rounded, 0 when total is 0
}

export interface ElementGapSummary {
  elementId: string;
  open: number;
  openMust: number;
}

export interface GapsSummary {
  total: number;
  open: number;
  inProgress: number;
  done: number;
  waived: number;
  openMust: number;
  unlinked: number;    // open requirements without any linked element
  byRegulation: RegulationGapSummary[];
  topElements: ElementGapSummary[];
}

const OPEN_STATUSES = new Set(['open', 'in_progress']);
const MS_PER_DAY = 86_400_000;

export interface ComplianceGapsResult {
  items: GapItem[];
  summary: GapsSummary;
  /** THE-423 Task 8: ContextTrace(feature:'gap') id for this read. Always set (best-effort recorder). */
  contextTraceId: string;
}

export async function computeComplianceGaps(
  projectId: string,
  filters: GapFilters = {},
): Promise<ComplianceGapsResult> {
  const query: Record<string, unknown> = {
    projectId: new mongoose.Types.ObjectId(projectId),
  };
  if (filters.regulationId) {
    if (mongoose.isValidObjectId(filters.regulationId)) {
      query.regulationId = new mongoose.Types.ObjectId(filters.regulationId);
    } else {
      // THE-390 P3: Nicht-ObjectId = kanonischer normId (`corpus:<source>` | `upload:<id>`).
      query.normId = filters.regulationId;
    }
  }
  if (filters.elementId) {
    query.linkedElementIds = filters.elementId;
  }
  if (filters.priority) {
    query.priority = filters.priority;
  }

  const requirements = await ComplianceRequirement.find(query).lean();

  // Titel-Auflösung: legacy über Regulation-Docs; Norm-basierte Requirements
  // (THE-390 P3) über die Norm-Facade — Gruppenschlüssel ist dann der normId.
  const legacyIds = [
    ...new Set(requirements.filter((r) => !r.normId).map((r) => String(r.regulationId))),
  ];
  // THE-423 (Task 8, DD-3 revised): retrieval stays the raw, ungoverned
  // `Regulation.find` exactly as before — gap persists no output, so there is
  // nothing to stamp and no reason to route through the governed reader
  // (that would add version-gating = a behavioral change). `source` /
  // `paragraphNumber` / `fullText` are additionally selected only to build
  // the ContextTrace's `consumed[]` below — the query filter is untouched.
  const regulations = await Regulation.find({ _id: { $in: legacyIds } })
    .select('title source paragraphNumber fullText')
    .lean();
  const regulationTitleById = new Map(regulations.map((r) => [String(r._id), r.title]));

  // Best-effort ContextTrace: one direct record per read, built ONLY from
  // regulations that actually carry both a derivable regulationKey (needs
  // source + paragraphNumber) and a version hash (needs fullText). Legacy
  // docs lacking those fields are skipped — consumed:[] is acceptable (mirrors
  // the oracle consumer). No AiTrace exists on this path (DD-5) → llmTraceRef
  // stays unset.
  const consumed: ConsumedRef[] = [];
  const seenKeys = new Set<string>();
  for (const reg of regulations) {
    if (!reg.source || !reg.paragraphNumber || !reg.fullText) continue;
    let regulationKey: string;
    try {
      regulationKey = buildRegulationKey(reg.source, reg.paragraphNumber);
    } catch {
      continue;
    }
    if (seenKeys.has(regulationKey)) continue;
    seenKeys.add(regulationKey);
    consumed.push({
      regulationKey,
      versionHash: computeVersionHash(reg.fullText),
      retrievalMethod: 'direct',
    });
  }
  const contextTraceId = await recordContextTrace({
    feature: 'gap',
    projectId,
    consumed,
  });

  const normIds = [...new Set(requirements.map((r) => r.normId).filter((n): n is string => !!n))];
  const normTitleById = new Map<string, string>();
  for (const normId of normIds) {
    const norm = await getPipelineNorm(projectId, normId);
    if (norm) normTitleById.set(normId, norm.name);
  }

  const now = Date.now();
  const items: GapItem[] = requirements.map((r) => ({
    _id: String(r._id),
    regulationId: r.normId ?? String(r.regulationId),
    regulationTitle: r.normId
      ? normTitleById.get(r.normId) ?? r.normId
      : regulationTitleById.get(String(r.regulationId)) ?? 'Unknown regulation',
    title: r.title,
    description: r.description,
    priority: r.priority,
    status: r.status,
    linkedElementIds: r.linkedElementIds ?? [],
    ageDays: r.createdAt ? Math.max(0, Math.floor((now - new Date(r.createdAt).getTime()) / MS_PER_DAY)) : 0,
    createdBy: r.createdBy,
    createdAt: r.createdAt,
  }));

  // ── Global counters ──
  const summary: GapsSummary = {
    total: items.length,
    open: items.filter((i) => i.status === 'open').length,
    inProgress: items.filter((i) => i.status === 'in_progress').length,
    done: items.filter((i) => i.status === 'done').length,
    waived: items.filter((i) => i.status === 'waived').length,
    openMust: items.filter((i) => OPEN_STATUSES.has(i.status) && i.priority === 'must').length,
    unlinked: items.filter((i) => OPEN_STATUSES.has(i.status) && i.linkedElementIds.length === 0).length,
    byRegulation: [],
    topElements: [],
  };

  // ── Per regulation (view A) ──
  const byReg = new Map<string, RegulationGapSummary>();
  for (const item of items) {
    let reg = byReg.get(item.regulationId);
    if (!reg) {
      reg = {
        regulationId: item.regulationId,
        regulationTitle: item.regulationTitle,
        total: 0,
        open: 0,
        done: 0,
        openMust: 0,
        pctOpen: 0,
      };
      byReg.set(item.regulationId, reg);
    }
    reg.total += 1;
    if (OPEN_STATUSES.has(item.status)) {
      reg.open += 1;
      if (item.priority === 'must') reg.openMust += 1;
    } else {
      reg.done += 1;
    }
  }
  for (const reg of byReg.values()) {
    reg.pctOpen = reg.total > 0 ? Math.round((reg.open / reg.total) * 100) : 0;
  }
  summary.byRegulation = [...byReg.values()].sort(
    (a, b) => b.openMust - a.openMust || b.open - a.open,
  );

  // ── Top elements with the most open (MUST) requirements (view C) ──
  const byElement = new Map<string, ElementGapSummary>();
  for (const item of items) {
    if (!OPEN_STATUSES.has(item.status)) continue;
    for (const elementId of item.linkedElementIds) {
      let el = byElement.get(elementId);
      if (!el) {
        el = { elementId, open: 0, openMust: 0 };
        byElement.set(elementId, el);
      }
      el.open += 1;
      if (item.priority === 'must') el.openMust += 1;
    }
  }
  summary.topElements = [...byElement.values()]
    .sort((a, b) => b.openMust - a.openMust || b.open - a.open)
    .slice(0, 5);

  return { items, summary, contextTraceId };
}
