/**
 * Compliance Gap Analysis — UC-GAP-001 (THE-307)
 *
 * Answers the auditor question "what is still missing?" on top of the
 * ComplianceRequirement entities generated by UC-REQGEN-001:
 *   - per regulation:  which requirements are still open, KPI "5 of 9 open"
 *   - per element:     which open requirements hang on element X
 *   - global:          which elements carry the most open MUST requirements
 *
 * Design constraint (THE-389): every number here is computed LIVE from the
 * ComplianceRequirement collection on each request — never from cached
 * pipeline stats. A wrong number in front of an auditor is worse than a
 * slower request.
 *
 * A "gap" is a requirement whose status is open or in_progress. done means
 * fulfilled; waived means deliberately closed with a decision — neither is
 * outstanding work.
 */
import mongoose from 'mongoose';
import { ComplianceRequirement } from '../models/ComplianceRequirement';
import { Regulation } from '../models/Regulation';

export interface GapFilters {
  regulationId?: string;
  elementId?: string;
  priority?: 'must' | 'should' | 'may';
}

export interface GapItem {
  _id: string;
  regulationId: string;
  regulationTitle: string;
  title: string;
  description: string;
  priority: 'must' | 'should' | 'may';
  status: 'open' | 'in_progress' | 'done' | 'waived';
  linkedElementIds: string[];
  ageDays: number;
  createdBy: string;
  createdAt: Date;
}

export interface RegulationGapSummary {
  regulationId: string;
  regulationTitle: string;
  total: number;
  open: number;        // open + in_progress
  done: number;        // done + waived
  openMust: number;
  pctOpen: number;     // rounded, 0 when total is 0
}

export interface ElementGapSummary {
  elementId: string;
  open: number;
  openMust: number;
}

export interface GapsSummary {
  total: number;
  open: number;
  inProgress: number;
  done: number;
  waived: number;
  openMust: number;
  unlinked: number;    // open requirements without any linked element
  byRegulation: RegulationGapSummary[];
  topElements: ElementGapSummary[];
}

const OPEN_STATUSES = new Set(['open', 'in_progress']);
const MS_PER_DAY = 86_400_000;

export async function computeComplianceGaps(
  projectId: string,
  filters: GapFilters = {},
): Promise<{ items: GapItem[]; summary: GapsSummary }> {
  const query: Record<string, unknown> = {
    projectId: new mongoose.Types.ObjectId(projectId),
  };
  if (filters.regulationId && mongoose.isValidObjectId(filters.regulationId)) {
    query.regulationId = new mongoose.Types.ObjectId(filters.regulationId);
  }
  if (filters.elementId) {
    query.linkedElementIds = filters.elementId;
  }
  if (filters.priority) {
    query.priority = filters.priority;
  }

  const requirements = await ComplianceRequirement.find(query).lean();

  const regulationIds = [...new Set(requirements.map((r) => String(r.regulationId)))];
  const regulations = await Regulation.find({ _id: { $in: regulationIds } })
    .select('title')
    .lean();
  const regulationTitleById = new Map(regulations.map((r) => [String(r._id), r.title]));

  const now = Date.now();
  const items: GapItem[] = requirements.map((r) => ({
    _id: String(r._id),
    regulationId: String(r.regulationId),
    regulationTitle: regulationTitleById.get(String(r.regulationId)) ?? 'Unknown regulation',
    title: r.title,
    description: r.description,
    priority: r.priority,
    status: r.status,
    linkedElementIds: r.linkedElementIds ?? [],
    ageDays: r.createdAt ? Math.max(0, Math.floor((now - new Date(r.createdAt).getTime()) / MS_PER_DAY)) : 0,
    createdBy: r.createdBy,
    createdAt: r.createdAt,
  }));

  // ── Global counters ──
  const summary: GapsSummary = {
    total: items.length,
    open: items.filter((i) => i.status === 'open').length,
    inProgress: items.filter((i) => i.status === 'in_progress').length,
    done: items.filter((i) => i.status === 'done').length,
    waived: items.filter((i) => i.status === 'waived').length,
    openMust: items.filter((i) => OPEN_STATUSES.has(i.status) && i.priority === 'must').length,
    unlinked: items.filter((i) => OPEN_STATUSES.has(i.status) && i.linkedElementIds.length === 0).length,
    byRegulation: [],
    topElements: [],
  };

  // ── Per regulation (view A) ──
  const byReg = new Map<string, RegulationGapSummary>();
  for (const item of items) {
    let reg = byReg.get(item.regulationId);
    if (!reg) {
      reg = {
        regulationId: item.regulationId,
        regulationTitle: item.regulationTitle,
        total: 0,
        open: 0,
        done: 0,
        openMust: 0,
        pctOpen: 0,
      };
      byReg.set(item.regulationId, reg);
    }
    reg.total += 1;
    if (OPEN_STATUSES.has(item.status)) {
      reg.open += 1;
      if (item.priority === 'must') reg.openMust += 1;
    } else {
      reg.done += 1;
    }
  }
  for (const reg of byReg.values()) {
    reg.pctOpen = reg.total > 0 ? Math.round((reg.open / reg.total) * 100) : 0;
  }
  summary.byRegulation = [...byReg.values()].sort(
    (a, b) => b.openMust - a.openMust || b.open - a.open,
  );

  // ── Top elements with the most open (MUST) requirements (view C) ──
  const byElement = new Map<string, ElementGapSummary>();
  for (const item of items) {
    if (!OPEN_STATUSES.has(item.status)) continue;
    for (const elementId of item.linkedElementIds) {
      let el = byElement.get(elementId);
      if (!el) {
        el = { elementId, open: 0, openMust: 0 };
        byElement.set(elementId, el);
      }
      el.open += 1;
      if (item.priority === 'must') el.openMust += 1;
    }
  }
  summary.topElements = [...byElement.values()]
    .sort((a, b) => b.openMust - a.openMust || b.open - a.open)
    .slice(0, 5);

  return { items, summary };
}
