import PDFDocument from 'pdfkit';
import { Project } from '../models/Project';
import { SimulationRun } from '../models/SimulationRun';
import { getXRaySummary, XRaySummary } from './xray.service';
import { assessRisk, estimateCosts, RiskAssessment } from './analytics.service';
import { checkCompliance, ComplianceReport } from './compliance.service';
import { runCypher } from '../config/neo4j';
import { TransformationRoadmap } from '../models/TransformationRoadmap';
import { OracleAssessment } from '../models/OracleAssessment';

// ─── Colors ──────────────────────────────────────────────
const ACCENT = '#00ff41';
const DARK = '#0a0a0a';
const GRAY = '#4a5a4a';
const LIGHT_GRAY = '#d0d0d0';
const WHITE = '#ffffff';
const RISK_COLORS: Record<string, string> = {
  critical: '#ef4444',
  high: '#f97316',
  medium: '#eab308',
  low: '#22c55e',
};
const RATING_COLORS: Record<string, string> = {
  green: '#22c55e',
  yellow: '#eab308',
  orange: '#f97316',
  red: '#ef4444',
};

// ─── Layout ──────────────────────────────────────────────
const PAGE_W = 595.28;
const MARGIN = 50;
const CONTENT_W = PAGE_W - MARGIN * 2;

// ─── Shared Helpers ──────────────────────────────────────

function drawHeader(doc: PDFKit.PDFDocument, title: string, subtitle?: string) {
  doc.save();
  doc.rect(0, 0, PAGE_W, 70).fill(DARK);
  doc.rect(0, 68, PAGE_W, 3).fill(ACCENT);
  doc.font('Helvetica-Bold').fontSize(18).fillColor(WHITE).text('TheArchitect', MARGIN, 20);
  doc.font('Helvetica').fontSize(10).fillColor(LIGHT_GRAY).text(title, MARGIN, 44);
  if (subtitle) {
    doc.font('Helvetica').fontSize(8).fillColor(GRAY).text(subtitle, PAGE_W - MARGIN - 200, 44, { width: 200, align: 'right' });
  }
  doc.restore();
  doc.y = 90;
}

function drawFooter(doc: PDFKit.PDFDocument, pageNum: number, classification?: string) {
  const y = 800;
  const savedY = doc.y;
  doc.save();
  doc.moveTo(MARGIN, y).lineTo(PAGE_W - MARGIN, y).strokeColor(LIGHT_GRAY).lineWidth(0.5).stroke();
  doc.font('Helvetica').fontSize(7).fillColor(GRAY);
  const footerLabel = classification
    ? `${classification} — Generated by TheArchitect`
    : 'Confidential — Generated by TheArchitect';
  doc.text(footerLabel, MARGIN, y + 6, { lineBreak: false });
  doc.text(`Page ${pageNum}`, PAGE_W - MARGIN - 50, y + 6, { width: 50, align: 'right', lineBreak: false });
  doc.restore();
  doc.y = savedY;
}

function drawSectionTitle(doc: PDFKit.PDFDocument, title: string) {
  checkPageBreak(doc, 40);
  doc.font('Helvetica-Bold').fontSize(12).fillColor(DARK).text(title, MARGIN, doc.y);
  doc.moveTo(MARGIN, doc.y + 2).lineTo(MARGIN + CONTENT_W, doc.y + 2).strokeColor(ACCENT).lineWidth(1).stroke();
  doc.moveDown(0.8);
}

function drawMetricCard(doc: PDFKit.PDFDocument, x: number, y: number, w: number, label: string, value: string, color?: string) {
  doc.save();
  doc.roundedRect(x, y, w, 50, 4).fillAndStroke('#f8fafc', LIGHT_GRAY);
  // Auto-shrink font for long values to prevent overflow
  const maxW = w - 16;
  let fontSize = 16;
  doc.font('Helvetica-Bold');
  while (fontSize > 7 && doc.fontSize(fontSize).widthOfString(value) > maxW) {
    fontSize -= 1;
  }
  const vOffset = fontSize < 12 ? 10 : 8; // center smaller text vertically
  doc.fontSize(fontSize).fillColor(color || DARK).text(value, x + 8, y + vOffset, { width: maxW, ellipsis: true });
  doc.font('Helvetica').fontSize(8).fillColor(GRAY).text(label, x + 8, y + 32, { width: maxW });
  doc.restore();
}

function drawRiskBadge(doc: PDFKit.PDFDocument, x: number, y: number, level: string) {
  const color = RISK_COLORS[level] || GRAY;
  doc.save();
  doc.circle(x + 4, y + 4, 4).fill(color);
  doc.font('Helvetica').fontSize(8).fillColor(DARK).text(level, x + 12, y, { width: 50 });
  doc.restore();
}

// KSU = Klassifizierungsstufe (BSI IT-Grundschutz)
const KSU_LABEL = 'KSU: C3 — VERTRAULICH';
const KSU_FULL = 'KSU: C3 — VERTRAULICH | BSI-Schutzbedarf: hoch | Nur für internen Gebrauch';

function drawClassificationBanner(doc: PDFKit.PDFDocument) {
  doc.save();
  doc.rect(0, 71, PAGE_W, 18).fill('#7f1d1d'); // dark-red banner
  doc.font('Helvetica-Bold').fontSize(8).fillColor('#fca5a5')
    .text(KSU_FULL, 0, 75, { width: PAGE_W, align: 'center' });
  doc.restore();
  doc.y = 96;
}

let currentPage = 1;
let currentClassification: string | undefined;

function addNewPage(doc: PDFKit.PDFDocument, title: string, subtitle?: string, classification?: string) {
  doc.addPage();
  currentPage++;
  drawHeader(doc, title, subtitle);
  if (classification) drawClassificationBanner(doc);
  drawFooter(doc, currentPage, classification);
}

function checkPageBreak(doc: PDFKit.PDFDocument, neededHeight: number = 60) {
  if (doc.y + neededHeight > 780) {
    addNewPage(doc, '', '', currentClassification);
    return true;
  }
  return false;
}

function drawTable(
  doc: PDFKit.PDFDocument,
  headers: string[],
  rows: string[][],
  colWidths: number[],
  title: string
) {
  const rowHeight = 18;
  const headerHeight = 22;
  let y = doc.y;

  // Header
  checkPageBreak(doc, headerHeight + rowHeight * 2);
  y = doc.y;
  doc.save();
  doc.rect(MARGIN, y, CONTENT_W, headerHeight).fill(DARK);
  let x = MARGIN;
  doc.font('Helvetica-Bold').fontSize(8).fillColor(WHITE);
  for (let i = 0; i < headers.length; i++) {
    doc.text(headers[i], x + 4, y + 6, { width: colWidths[i] - 8 });
    x += colWidths[i];
  }
  doc.restore();
  y += headerHeight;

  // Rows
  for (let r = 0; r < rows.length; r++) {
    if (y + rowHeight > 780) {
      addNewPage(doc, title, '');
      y = doc.y;
      // Re-draw header
      doc.save();
      doc.rect(MARGIN, y, CONTENT_W, headerHeight).fill(DARK);
      x = MARGIN;
      doc.font('Helvetica-Bold').fontSize(8).fillColor(WHITE);
      for (let i = 0; i < headers.length; i++) {
        doc.text(headers[i], x + 4, y + 6, { width: colWidths[i] - 8 });
        x += colWidths[i];
      }
      doc.restore();
      y += headerHeight;
    }

    if (r % 2 === 0) {
      doc.save();
      doc.rect(MARGIN, y, CONTENT_W, rowHeight).fill('#f8fafc');
      doc.restore();
    }
    x = MARGIN;
    doc.font('Helvetica').fontSize(8).fillColor(DARK);
    for (let i = 0; i < rows[r].length; i++) {
      doc.text(rows[r][i] || '-', x + 4, y + 5, { width: colWidths[i] - 8, height: rowHeight - 6, ellipsis: true, lineBreak: false });
      x += colWidths[i];
    }
    y += rowHeight;
  }

  doc.y = y + 10;
}

function drawBarChart(doc: PDFKit.PDFDocument, x: number, y: number, w: number, data: { label: string; value: number; color?: string }[]) {
  const barH = 14;
  const gap = 6;
  const maxVal = Math.max(...data.map((d) => d.value), 1);
  const labelW = 100;
  const barW = w - labelW - 50;

  for (let i = 0; i < data.length; i++) {
    const by = y + i * (barH + gap);
    doc.font('Helvetica').fontSize(8).fillColor(DARK).text(data[i].label, x, by + 2, { width: labelW });
    const fillW = (data[i].value / maxVal) * barW;
    doc.save();
    doc.roundedRect(x + labelW, by, barW, barH, 2).fill('#e2e8f0');
    if (fillW > 0) {
      doc.roundedRect(x + labelW, by, Math.max(fillW, 4), barH, 2).fill(data[i].color || ACCENT);
    }
    doc.restore();
    doc.font('Helvetica').fontSize(8).fillColor(DARK).text(formatNumber(data[i].value), x + labelW + barW + 4, by + 2);
  }

  doc.y = y + data.length * (barH + gap) + 10;
}

function formatNumber(n: number): string {
  if (n >= 1_000_000) return `€${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `€${(n / 1_000).toFixed(0)}K`;
  return `€${n}`;
}

function formatPercent(n: number): string {
  return `${Math.round(n)}%`;
}

// ─── Executive Report ────────────────────────────────────

async function renderExecutiveReport(doc: PDFKit.PDFDocument, project: { name: string; description?: string }, projectId: string) {
  const subtitle = `Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`;
  drawHeader(doc, `Executive Summary — ${project.name}`, subtitle);
  drawFooter(doc, 1);

  let xray: XRaySummary;
  let compliance: ComplianceReport;
  try {
    [xray, compliance] = await Promise.all([
      getXRaySummary(projectId),
      checkCompliance(projectId),
    ]);
  } catch {
    doc.font('Helvetica').fontSize(10).fillColor(DARK).text('No architecture elements found. Import elements to generate a report.', MARGIN, doc.y);
    return;
  }

  // Key Metrics (2x2 grid)
  drawSectionTitle(doc, 'Key Metrics');
  const metricY = doc.y;
  const cardW = (CONTENT_W - 10) / 2;
  drawMetricCard(doc, MARGIN, metricY, cardW, 'Total Risk Exposure', formatNumber(xray.metrics.totalRiskExposure), '#ef4444');
  drawMetricCard(doc, MARGIN + cardW + 10, metricY, cardW, 'Transformation Progress', formatPercent(xray.metrics.transformationProgress), ACCENT);
  drawMetricCard(doc, MARGIN, metricY + 60, cardW, 'Time to Target', `${xray.metrics.timeToTarget} months`);
  drawMetricCard(doc, MARGIN + cardW + 10, metricY + 60, cardW, 'Decision Confidence', formatPercent(xray.metrics.decisionConfidence), '#22c55e');
  doc.y = metricY + 130;

  // Top Risk Elements
  drawSectionTitle(doc, 'Top Risk Elements');
  const riskRows = xray.riskElements.slice(0, 10).map((e) => [
    e.name,
    e.type,
    e.riskScore.toFixed(1),
    e.riskScore >= 7 ? 'critical' : e.riskScore >= 5 ? 'high' : e.riskScore >= 3 ? 'medium' : 'low',
  ]);
  if (riskRows.length > 0) {
    drawTable(doc, ['Name', 'Type', 'Score', 'Risk Level'], riskRows, [180, 120, 60, 80], 'Executive Summary');
  } else {
    doc.font('Helvetica').fontSize(9).fillColor(GRAY).text('No risk elements found.', MARGIN, doc.y);
    doc.moveDown();
  }

  // Page 2: Cost + Compliance
  addNewPage(doc, `Executive Summary — ${project.name}`, subtitle);

  // Cost Overview
  drawSectionTitle(doc, 'Cost Overview');
  const costY = doc.y;
  drawMetricCard(doc, MARGIN, costY, cardW, 'Total TCO', formatNumber(xray.costSummary.totalCost));
  drawMetricCard(doc, MARGIN + cardW + 10, costY, cardW, 'Optimization Potential', formatNumber(xray.costSummary.optimizationTotal), '#22c55e');
  doc.y = costY + 70;

  // Cost by Category
  const categories = Object.entries(xray.costSummary.byCategory);
  if (categories.length > 0) {
    drawSectionTitle(doc, 'Cost by Category');
    drawBarChart(doc, MARGIN, doc.y, CONTENT_W, categories.map(([label, value]) => ({ label, value })));
  }

  // Compliance
  drawSectionTitle(doc, 'Compliance');
  const compY = doc.y;
  const scoreColor = compliance.summary.complianceScore >= 80 ? '#22c55e' : compliance.summary.complianceScore >= 50 ? '#eab308' : '#ef4444';
  drawMetricCard(doc, MARGIN, compY, cardW, 'Compliance Score', formatPercent(compliance.summary.complianceScore), scoreColor);
  drawMetricCard(doc, MARGIN + cardW + 10, compY, cardW, 'Violations',
    `${compliance.summary.errors} errors, ${compliance.summary.warnings} warnings`);
  doc.y = compY + 70;

  if (compliance.violations.length > 0) {
    const violationRows = compliance.violations.slice(0, 15).map((v) => [
      v.elementName,
      v.severity,
      v.policyName,
      v.message.slice(0, 60),
    ]);
    drawTable(doc, ['Element', 'Severity', 'Policy', 'Message'], violationRows, [120, 60, 120, 195], 'Executive Summary');
  }
}

// ─── Simulation Report ───────────────────────────────────

async function renderSimulationReport(doc: PDFKit.PDFDocument, project: { name: string }, run: Record<string, unknown>) {
  const result = run.result as Record<string, unknown> | undefined;
  const config = run.config as Record<string, unknown> | undefined;
  const subtitle = `Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`;

  drawHeader(doc, `MiroFish Simulation — ${project.name}`, subtitle);
  drawFooter(doc, 1);

  // Scenario Info
  drawSectionTitle(doc, 'Scenario Overview');
  doc.font('Helvetica').fontSize(9).fillColor(DARK);
  doc.text(`Simulation: ${run.name || 'Unnamed'}`, MARGIN, doc.y);
  doc.text(`Scenario Type: ${run.scenarioType || '-'}`, MARGIN, doc.y);
  doc.text(`Status: ${run.status || '-'}`, MARGIN, doc.y);
  if (config) {
    doc.text(`Description: ${(config as Record<string, unknown>).scenarioDescription || '-'}`, MARGIN, doc.y);
    doc.text(`Max Rounds: ${(config as Record<string, unknown>).maxRounds || '-'}`, MARGIN, doc.y);
  }
  doc.moveDown();

  if (!result) {
    doc.font('Helvetica').fontSize(10).fillColor(GRAY).text('Simulation has not completed yet.', MARGIN, doc.y);
    return;
  }

  // Outcome
  drawSectionTitle(doc, 'Outcome');
  doc.font('Helvetica-Bold').fontSize(11).fillColor(DARK).text(`${(result.outcome as string || 'unknown').toUpperCase()}`, MARGIN, doc.y);
  doc.moveDown(0.3);
  if (result.summary) {
    doc.font('Helvetica').fontSize(9).fillColor(DARK).text(result.summary as string, MARGIN, doc.y, { width: CONTENT_W });
  }
  doc.moveDown();

  // Fatigue Scorecard
  const fatigue = result.fatigue as Record<string, unknown> | undefined;
  if (fatigue) {
    drawSectionTitle(doc, 'Fatigue Scorecard');
    const fatigueY = doc.y;
    const cardW3 = (CONTENT_W - 20) / 3;
    const rating = (fatigue.rating as string) || 'green';
    const ratingColor = RATING_COLORS[rating] || GRAY;
    drawMetricCard(doc, MARGIN, fatigueY, cardW3, 'Fatigue Index', `${Math.round((fatigue.globalIndex as number || 0) * 100)}%`, ratingColor);
    drawMetricCard(doc, MARGIN + cardW3 + 10, fatigueY, cardW3, 'Projected Delay', `+${fatigue.totalProjectedDelayMonths || 0} months`, '#f97316');
    drawMetricCard(doc, MARGIN + (cardW3 + 10) * 2, fatigueY, cardW3, 'Budget at Risk', formatNumber((fatigue.budgetAtRisk as number) || 0), '#ef4444');
    doc.y = fatigueY + 70;

    // Recommendation
    if (fatigue.recommendation) {
      drawSectionTitle(doc, 'Recommendation');
      doc.font('Helvetica').fontSize(9).fillColor(DARK).text(fatigue.recommendation as string, MARGIN, doc.y, { width: CONTENT_W });
      doc.moveDown();
    }

    // Per-Agent Fatigue
    const perAgent = fatigue.perAgent as Array<Record<string, unknown>> | undefined;
    if (perAgent && perAgent.length > 0) {
      addNewPage(doc, `MiroFish Simulation — ${project.name}`, subtitle);
      drawSectionTitle(doc, 'Stakeholder Fatigue Analysis');

      const agentRows = perAgent.map((a) => [
        a.agentName as string || '-',
        `${Math.round((a.fatigueIndex as number || 0) * 100)}%`,
        `${Math.round((a.concurrencyLoad as number || 0) * 100)}%`,
        `${Math.round((a.negotiationDrag as number || 0) * 100)}%`,
        `${Math.round((a.constraintPressure as number || 0) * 100)}%`,
        a.projectedDelayMonths ? `+${a.projectedDelayMonths}m` : '-',
      ]);
      drawTable(doc, ['Agent', 'Fatigue', 'Concurrency', 'Negotiation', 'Constraint', 'Delay'],
        agentRows, [120, 70, 75, 80, 75, 75], 'Simulation Report');
    }

    // Bottleneck Elements
    const perElement = fatigue.perElement as Array<Record<string, unknown>> | undefined;
    if (perElement && perElement.length > 0) {
      drawSectionTitle(doc, 'Bottleneck Elements');
      const elementRows = perElement.slice(0, 10).map((e) => {
        const agents = (e.involvedAgents as string[]) || [];
        const maxShow = 3;
        const agentStr = agents.length <= maxShow
          ? agents.join(', ')
          : agents.slice(0, maxShow).join(', ') + ` +${agents.length - maxShow} more`;
        return [
          e.elementName as string || '-',
          `${Math.round((e.negotiationDrag as number || 0) * 100)}%`,
          `${e.conflictRounds || 0}`,
          agentStr,
          e.projectedDelayMonths ? `+${e.projectedDelayMonths}m` : '-',
        ];
      });
      drawTable(doc, ['Element', 'Negotiation', 'Conflicts', 'Agents', 'Delay'],
        elementRows, [140, 75, 65, 140, 75], 'Simulation Report');
    }
  }

  // Emergence Metrics
  const emergence = result.emergenceMetrics as Record<string, unknown> | undefined;
  if (emergence) {
    checkPageBreak(doc, 100);
    drawSectionTitle(doc, 'Emergence Metrics');
    const emY = doc.y;
    const cardW4 = (CONTENT_W - 30) / 4;
    drawMetricCard(doc, MARGIN, emY, cardW4, 'Consensus Score', formatPercent((emergence.consensusScore as number || 0) * 100));
    drawMetricCard(doc, MARGIN + cardW4 + 10, emY, cardW4, 'Deadlocks', `${emergence.deadlockCount || 0}`);
    drawMetricCard(doc, MARGIN + (cardW4 + 10) * 2, emY, cardW4, 'Avg Rounds', `${(emergence.avgRoundsToConsensus as number || 0).toFixed(1)}`);
    drawMetricCard(doc, MARGIN + (cardW4 + 10) * 3, emY, cardW4, 'Hallucinations Blocked', `${emergence.blockedHallucinations || 0}`);
    doc.y = emY + 70;
  }

  // ─── EU AI Act compliance sections (Patch 8) ─────────────────
  // Mirrors the Oracle report structure so MiroFish runs are equally
  // auditable. Pulls per-round agent reasoning + actions for the
  // detailed sections.

  const rounds = (run.rounds as Array<Record<string, unknown>>) || [];
  const runConfig = run.config as Record<string, unknown> | undefined;
  const personas = (runConfig?.agents as Array<Record<string, unknown>>) || [];

  // Build per-agent aggregate from rounds (last position + all reasoning)
  type AgentAggregate = {
    agentId: string;
    agentName: string;
    persona?: Record<string, unknown>;
    finalPosition: string;
    totalActions: number;
    rejectedActions: number;
    modifiedActions: number;
    reasoning: string[];
    actionDetails: Array<{ round: number; type: string; element: string; reasoning: string; position: string }>;
  };
  const agentAggregates = new Map<string, AgentAggregate>();
  for (const persona of personas) {
    const id = String(persona.id || '');
    if (!id) continue;
    agentAggregates.set(id, {
      agentId: id,
      agentName: String(persona.name || id),
      persona,
      finalPosition: 'unknown',
      totalActions: 0,
      rejectedActions: 0,
      modifiedActions: 0,
      reasoning: [],
      actionDetails: [],
    });
  }
  for (const round of rounds) {
    const roundNum = Number(round.roundNumber || 0);
    const turns = (round.agentTurns as Array<Record<string, unknown>>) || [];
    for (const turn of turns) {
      const id = String(turn.agentPersonaId || '');
      const agg = agentAggregates.get(id);
      if (!agg) continue;
      const position = String(turn.position || 'abstain');
      agg.finalPosition = position; // last turn wins
      const reasoning = String(turn.reasoning || '');
      if (reasoning) agg.reasoning.push(`R${roundNum + 1}: ${reasoning}`);
      const validated = (turn.validatedActions as Array<Record<string, unknown>>) || [];
      agg.totalActions += validated.length;
      for (const a of validated) {
        if (position === 'reject') agg.rejectedActions += 1;
        if (position === 'modify') agg.modifiedActions += 1;
        agg.actionDetails.push({
          round: roundNum + 1,
          type: String(a.type || ''),
          element: String(a.targetElementName || ''),
          reasoning: String(a.reasoning || ''),
          position,
        });
      }
    }
  }

  // ─── Page: Detailed Stakeholder Reasoning ───
  if (agentAggregates.size > 0) {
    addNewPage(doc, `MiroFish Simulation — ${project.name}`, subtitle);
    drawSectionTitle(doc, 'Detailed Stakeholder Reasoning');

    for (const agg of agentAggregates.values()) {
      checkPageBreak(doc, 120);
      const persona = agg.persona || {};
      const posColor = POSITION_COLORS[agg.finalPosition] || GRAY;

      doc.font('Helvetica-Bold').fontSize(10).fillColor(posColor)
        .text(`${agg.agentName} — ${agg.finalPosition.toUpperCase()} (${agg.actionDetails.length} actions across ${rounds.length} rounds)`, MARGIN);
      doc.moveDown(0.2);

      // Context box
      doc.font('Helvetica').fontSize(7).fillColor(GRAY);
      const ctx = [
        persona.riskThreshold ? `Risk threshold: ${persona.riskThreshold}` : '',
        persona.budgetConstraint ? `Budget: $${Number(persona.budgetConstraint).toLocaleString()}` : '',
        persona.expectedCapacity ? `Capacity: ${persona.expectedCapacity} parallel` : '',
        Array.isArray(persona.visibleLayers) ? `Layers: ${(persona.visibleLayers as string[]).join(', ')}` : '',
      ].filter(Boolean).join(' | ');
      if (ctx) {
        doc.text(ctx, MARGIN);
        doc.moveDown(0.2);
      }

      // Round-by-round reasoning
      doc.font('Helvetica').fontSize(9).fillColor(DARK);
      for (const r of agg.reasoning.slice(0, 5)) {
        checkPageBreak(doc, 24);
        doc.text(r, MARGIN, doc.y, { width: CONTENT_W });
        doc.moveDown(0.2);
      }

      // Top action details
      const topActions = agg.actionDetails.slice(0, 3);
      if (topActions.length > 0) {
        doc.font('Helvetica').fontSize(8).fillColor(GRAY);
        for (const a of topActions) {
          checkPageBreak(doc, 14);
          doc.text(`  → R${a.round} ${a.position.toUpperCase()} on "${a.element}": ${a.reasoning.slice(0, 200)}`, MARGIN, doc.y, { width: CONTENT_W - 10 });
          doc.moveDown(0.15);
        }
      }
      doc.moveDown(0.5);
    }
  }

  // ─── Page: Resistance Factors + Next Steps + Methodology + Audit ───
  addNewPage(doc, `MiroFish Simulation — ${project.name}`, subtitle);

  // Resistance Factors — prefer the LLM-extracted ones from Patch 9, fall
  // back to deriving from REJECT/MODIFY actions for pre-Patch-9 historical runs.
  const llmResistanceFactors = (result.resistanceFactors as Array<Record<string, unknown>> | undefined) || [];
  type RF = { factor: string; severity: string; source: string };
  let resistanceFactors: RF[] = [];
  if (llmResistanceFactors.length > 0) {
    resistanceFactors = llmResistanceFactors.slice(0, 20).map((f) => ({
      factor: String(f.factor || ''),
      severity: String(f.severity || 'medium'),
      source: String(f.source || ''),
    }));
  } else {
    for (const agg of agentAggregates.values()) {
      for (const a of agg.actionDetails) {
        if (a.position !== 'reject' && a.position !== 'modify') continue;
        const severity = a.position === 'reject' ? 'high' : 'medium';
        resistanceFactors.push({
          factor: `${a.position.toUpperCase()} on "${a.element}": ${a.reasoning.slice(0, 110)}`,
          severity,
          source: agg.agentName,
        });
        if (resistanceFactors.length >= 20) break;
      }
      if (resistanceFactors.length >= 20) break;
    }
  }

  if (resistanceFactors.length > 0) {
    drawSectionTitle(doc, 'Resistance Factors');
    drawTable(doc,
      ['Factor', 'Severity', 'Source'],
      resistanceFactors.map((f) => [f.factor.slice(0, 90), f.severity, f.source.slice(0, 30)]),
      [310, 50, 135],
      'Resistance Factors',
    );
    doc.moveDown(0.6);
  }

  // Next Steps — LLM-reasoned recommendations (Patch 9). Falls back to the
  // heuristic mitigation strings if the simulation predates Patch 9.
  const nextSteps = (result.nextSteps as Array<Record<string, unknown>> | undefined) || [];

  if (nextSteps.length > 0) {
    drawSectionTitle(doc, 'Next Steps (AI-recommended actions)');
    doc.font('Helvetica').fontSize(8).fillColor(GRAY);
    doc.text('Each step targets a specific resistance factor or bottleneck identified above. Owner / cost / timeline are advisory and require human review before scheduling.', MARGIN, doc.y, { width: CONTENT_W });
    doc.moveDown(0.4);

    drawTable(doc,
      ['#', 'Category', 'Action', 'Owner', 'Cost', 'Timeline'],
      nextSteps.map((s, i) => [
        String(i + 1),
        String(s.category || 'mitigation').replace('_', ' '),
        String(s.action || '').slice(0, 110),
        String(s.ownerHint || '—').slice(0, 28),
        String(s.costEstimateRange || '—').slice(0, 18),
        String(s.timelineHint || '—').slice(0, 18),
      ]),
      [20, 65, 230, 75, 50, 55],
      'Next Steps',
    );
    doc.moveDown(0.5);

    // Per-step rationale block — gives the WHY behind each recommendation
    doc.font('Helvetica').fontSize(8).fillColor(GRAY);
    nextSteps.forEach((s, i) => {
      const rationale = String(s.rationale || '').trim();
      if (!rationale) return;
      checkPageBreak(doc, 18);
      doc.text(`${i + 1}. Why: ${rationale}`, MARGIN, doc.y, { width: CONTENT_W });
      doc.moveDown(0.2);
    });
    doc.moveDown(0.4);
  } else {
    // Fallback heuristic mitigations for pre-Patch-9 runs
    const mitigations: string[] = [];
    if (fatigue?.recommendation) {
      mitigations.push(String(fatigue.recommendation));
    }
    const overloadedAgents = (fatigue?.perAgent as Array<Record<string, unknown>> | undefined)
      ?.filter((a) => Number(a.concurrencyLoad || 0) >= 0.8)
      ?.map((a) => String(a.agentName || '')) || [];
    if (overloadedAgents.length > 0) {
      mitigations.push(`Phase work for overloaded stakeholders (${overloadedAgents.join(', ')}) to reduce concurrent load below 80%.`);
    }
    const topBottleneck = (fatigue?.perElement as Array<Record<string, unknown>> | undefined)?.[0];
    if (topBottleneck && Number(topBottleneck.conflictRounds || 0) >= 2) {
      mitigations.push(`Schedule a stakeholder workshop for "${topBottleneck.elementName}" (${topBottleneck.conflictRounds} conflict rounds) to resolve the deadlock pattern before implementation.`);
    }
    if (resistanceFactors.length >= 5) {
      mitigations.push(`Document each REJECT/MODIFY rationale in a decision log; assign a change champion to address each before progressing.`);
    }
    if (mitigations.length > 0) {
      drawSectionTitle(doc, 'Mitigation Suggestions (heuristic — Patch 9 not yet active for this run)');
      doc.font('Helvetica').fontSize(9).fillColor(DARK);
      mitigations.forEach((m, i) => {
        checkPageBreak(doc, 20);
        doc.text(`${i + 1}. ${m}`, MARGIN, doc.y, { width: CONTENT_W });
        doc.moveDown(0.3);
      });
      doc.moveDown(0.5);
    }
  }

  // Scoring Methodology
  drawSectionTitle(doc, 'Scoring Methodology (Compliance)');
  doc.font('Helvetica').fontSize(9).fillColor(DARK);
  doc.text('Method: Composite Fatigue Index (3-factor model)', MARGIN);
  doc.text('Formula: FatigueIndex = 0.4 × ConcurrencyLoad + 0.4 × NegotiationDrag + 0.2 × ConstraintPressure', MARGIN);
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(8).fillColor(GRAY);
  doc.text('Factor definitions:', MARGIN);
  doc.text('  - ConcurrencyLoad = parallel changes / expected capacity (capped at 1.0)', MARGIN);
  doc.text('  - NegotiationDrag = conflict rounds touched / total rounds elapsed', MARGIN);
  doc.text('  - ConstraintPressure = budget/risk-threshold violations / total proposals', MARGIN);
  doc.moveDown(0.3);
  doc.text('Conflict definition: any round where 2+ agents take distinct positions on the same element.', MARGIN);
  doc.text('Deadlock: a conflict round where at least one agent rejects while at least one approves.', MARGIN);
  doc.text('Hallucination: an agent action targeting an element ID not in the agent\'s visible architecture (blocked by validator).', MARGIN);
  doc.moveDown(0.3);
  doc.text('Rating thresholds: Green < 0.30 | Yellow 0.30-0.59 | Orange 0.60-0.79 | Red >= 0.80', MARGIN);
  doc.moveDown(0.5);

  // Audit Metadata (Patch 8 — EU AI Act Art. 12 record-keeping)
  drawSectionTitle(doc, 'Audit Metadata');
  doc.font('Helvetica').fontSize(8).fillColor(GRAY);
  doc.text(`Run ID: ${run._id || 'unknown'}`, MARGIN);
  doc.text(`Run Name: ${run.name || '-'}`, MARGIN);
  doc.text(`Created: ${run.createdAt ? new Date(run.createdAt as Date).toISOString() : '-'}`, MARGIN);
  doc.text(`Status: ${run.status || '-'}`, MARGIN);
  doc.text(`LLM Provider: ${process.env.OPENAI_API_KEY ? 'openai' : process.env.ANTHROPIC_API_KEY ? 'anthropic' : 'unknown'}`, MARGIN);
  doc.text(`Model: ${process.env.OPENAI_MODEL || process.env.ANTHROPIC_MODEL || 'default'}`, MARGIN);
  doc.text(`Project: ${project.name}`, MARGIN);
  doc.text(`Total Tokens Used: ${run.totalTokensUsed || 0}`, MARGIN);
  doc.text(`Total Duration: ${Math.round(Number(run.totalDurationMs || 0) / 1000)}s`, MARGIN);
  doc.text(`Rounds Executed: ${rounds.length} of ${(runConfig?.maxRounds as number) || 5}`, MARGIN);
  doc.text(`Personas: ${personas.length}`, MARGIN);

  // ─── Page: EU AI Act Compliance ───
  addNewPage(doc, `MiroFish Simulation — ${project.name}`, subtitle);

  drawSectionTitle(doc, 'System Risk Classification (EU AI Act Art. 6-7)');
  doc.font('Helvetica').fontSize(9).fillColor(DARK);
  doc.text('Classification Level: limited (decision support, not autonomous)', MARGIN);
  doc.text('Human Oversight Required: Yes', MARGIN);
  doc.text('Legal Reference: EU AI Act 2024/1689, Art. 6(2), Art. 52(1)', MARGIN);
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(8).fillColor(GRAY);
  doc.text('MiroFish multi-agent simulations produce stakeholder consensus signals for human enterprise architects. The system does NOT autonomously change architecture state, allocate budgets, or execute decisions. All recommended actions require explicit human approval before being applied to the architecture model.', MARGIN, doc.y, { width: CONTENT_W });
  doc.moveDown(0.6);

  drawSectionTitle(doc, 'Human Oversight Status (EU AI Act Art. 14)');
  doc.font('Helvetica-Bold').fontSize(10).fillColor('#eab308').text('PENDING REVIEW', MARGIN);
  doc.moveDown(0.2);
  doc.font('Helvetica').fontSize(8).fillColor(GRAY);
  doc.text('This simulation report must be reviewed by an authorized enterprise architect before any of its recommended actions are applied to the architecture model. The reviewer should evaluate the validity of stakeholder reasoning, the proportionality of identified resistance factors, and whether the proposed mitigations are operationally feasible. Reviewer sign-off must be documented in the project audit log.', MARGIN, doc.y, { width: CONTENT_W });
  doc.moveDown(0.6);

  drawSectionTitle(doc, 'Transparency Notice (EU AI Act Art. 13)');
  doc.font('Helvetica').fontSize(8).fillColor(GRAY);
  doc.text('All stakeholder reasoning shown in this report was generated by a Large Language Model conditioned on the persona definition, project vision/principles, and visible architecture context. Reasoning is non-deterministic; re-running the same scenario may produce different specific phrasings while preserving the underlying position pattern. The scoring methodology section above describes the deterministic numerical aggregation applied to model output.', MARGIN, doc.y, { width: CONTENT_W });
}

// ─── Inventory Report ────────────────────────────────────

async function renderInventoryReport(doc: PDFKit.PDFDocument, project: { name: string }, projectId: string) {
  const subtitle = `Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`;
  drawHeader(doc, `Architecture Inventory — ${project.name}`, subtitle);
  drawFooter(doc, 1);

  // Fetch elements from Neo4j
  const records = await runCypher(
    `MATCH (e:ArchitectureElement {projectId: $projectId})
     RETURN e.id as id, e.name as name, e.type as type, e.layer as layer,
            e.status as status, e.riskLevel as riskLevel,
            e.maturityLevel as maturity, e.togafDomain as domain
     ORDER BY e.layer, e.riskLevel DESC`,
    { projectId }
  );

  interface ElementRow {
    name: string;
    type: string;
    layer: string;
    status: string;
    riskLevel: string;
    maturity: number;
    domain: string;
  }

  const elements: ElementRow[] = records.map((r) => ({
    name: r.get('name') || '-',
    type: r.get('type') || '-',
    layer: r.get('layer') || '-',
    status: r.get('status') || '-',
    riskLevel: r.get('riskLevel') || 'low',
    maturity: r.get('maturity')?.toNumber?.() || r.get('maturity') || 3,
    domain: r.get('domain') || '-',
  }));

  if (elements.length === 0) {
    doc.font('Helvetica').fontSize(10).fillColor(DARK).text('No architecture elements found. Import elements to generate an inventory.', MARGIN, doc.y);
    return;
  }

  // Summary metrics
  drawSectionTitle(doc, 'Summary');
  const layers = ['strategy', 'business', 'information', 'application', 'technology'];
  const layerCounts = layers.map((l) => ({ label: l, value: elements.filter((e) => e.layer === l).length }));
  const avgMaturity = elements.reduce((s, e) => s + e.maturity, 0) / elements.length;
  const riskCounts = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const e of elements) {
    const key = e.riskLevel as keyof typeof riskCounts;
    if (key in riskCounts) riskCounts[key]++;
  }

  const summaryY = doc.y;
  const cardW3 = (CONTENT_W - 20) / 3;
  drawMetricCard(doc, MARGIN, summaryY, cardW3, 'Total Elements', `${elements.length}`);
  drawMetricCard(doc, MARGIN + cardW3 + 10, summaryY, cardW3, 'Avg Maturity', avgMaturity.toFixed(1));
  drawMetricCard(doc, MARGIN + (cardW3 + 10) * 2, summaryY, cardW3, 'Critical/High Risk', `${riskCounts.critical + riskCounts.high}`, '#ef4444');
  doc.y = summaryY + 70;

  // Elements by Layer chart
  drawSectionTitle(doc, 'Elements by Layer');
  drawBarChart(doc, MARGIN, doc.y, CONTENT_W, layerCounts.filter((l) => l.value > 0).map((l) => ({
    label: l.label.charAt(0).toUpperCase() + l.label.slice(1),
    value: l.value,
    color: ACCENT,
  })));

  // Tables per layer
  for (const layer of layers) {
    const layerElements = elements.filter((e) => e.layer === layer);
    if (layerElements.length === 0) continue;

    checkPageBreak(doc, 60);
    drawSectionTitle(doc, `${layer.charAt(0).toUpperCase() + layer.slice(1)} Layer (${layerElements.length})`);

    const rows = layerElements.map((e) => [
      e.name,
      e.type,
      e.status,
      e.riskLevel,
      `${e.maturity}/5`,
      e.domain,
    ]);
    drawTable(doc, ['Name', 'Type', 'Status', 'Risk', 'Maturity', 'Domain'],
      rows, [130, 95, 75, 60, 55, 80], 'Architecture Inventory');
  }
}

// ─── Roadmap Report ──────────────────────────────────────

async function renderRoadmapReport(doc: PDFKit.PDFDocument, project: { name: string }, roadmapId: string) {
  const roadmap = await TransformationRoadmap.findById(roadmapId).lean();
  if (!roadmap) throw new Error('Roadmap not found');

  const subtitle = `Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`;
  const strategyLabel = (roadmap.config as any)?.strategy || 'balanced';

  // Page 1: Executive Summary
  drawHeader(doc, `Transformation Roadmap — ${project.name}`, subtitle);
  drawFooter(doc, 1);

  drawSectionTitle(doc, 'Executive Summary');

  const summary = roadmap.summary as any || {};
  const costConfidence = summary.costConfidence || {};
  const metricY = doc.y;
  const cardW = (CONTENT_W - 10) / 2;

  drawMetricCard(doc, MARGIN, metricY, cardW, 'Total Cost (P50)',
    formatNumber(costConfidence.p50 || summary.totalCost || 0), '#f97316');
  drawMetricCard(doc, MARGIN + cardW + 10, metricY, cardW, 'Duration',
    `${summary.totalDurationMonths || 0} months`, '#3b82f6');
  drawMetricCard(doc, MARGIN, metricY + 60, cardW, 'Risk Reduction',
    `-${summary.riskReduction || 0}%`, '#22c55e');
  drawMetricCard(doc, MARGIN + cardW + 10, metricY + 60, cardW, 'Violations Fixed',
    `${summary.complianceImprovement || 0}`, '#a855f7');
  doc.y = metricY + 130;

  // Strategy & Config
  doc.font('Helvetica').fontSize(9).fillColor(DARK);
  doc.text(`Strategy: ${strategyLabel.charAt(0).toUpperCase() + strategyLabel.slice(1)}`, MARGIN, doc.y);
  doc.text(`Waves: ${summary.waveCount || 0}  |  Elements: ${summary.totalElements || 0}`, MARGIN, doc.y);
  if (costConfidence.p10 && costConfidence.p90) {
    doc.text(`Cost Range: ${formatNumber(costConfidence.p10)} (P10) — ${formatNumber(costConfidence.p90)} (P90)`, MARGIN, doc.y);
  }
  doc.moveDown();

  // Wave Summary Table
  const waves = (roadmap.waves as any[]) || [];
  if (waves.length > 0) {
    drawSectionTitle(doc, 'Wave Overview');
    const waveRows = waves.map((w: any) => [
      `Wave ${w.waveNumber}`,
      w.name || '-',
      `${w.elements?.length || 0}`,
      formatNumber(w.metrics?.totalCost || 0),
      `${w.estimatedDurationMonths || 0} mo`,
      `${(w.metrics?.riskDelta || 0) > 0 ? '+' : ''}${(w.metrics?.riskDelta || 0).toFixed(0)}%`,
    ]);
    drawTable(doc, ['Wave', 'Name', 'Elements', 'Cost', 'Duration', 'Risk Delta'],
      waveRows, [60, 140, 60, 80, 65, 90], 'Transformation Roadmap');
  }

  // Page 2+: Wave Details
  for (const wave of waves) {
    addNewPage(doc, `Transformation Roadmap — ${project.name}`, subtitle);
    drawSectionTitle(doc, `Wave ${wave.waveNumber}: ${wave.name || 'Unnamed'}`);

    if (wave.description) {
      doc.font('Helvetica').fontSize(9).fillColor(DARK).text(wave.description, MARGIN, doc.y, { width: CONTENT_W });
      doc.moveDown(0.5);
    }

    // Wave metrics
    const wMetrics = wave.metrics || {};
    const wMetricY = doc.y;
    const cardW3 = (CONTENT_W - 20) / 3;
    drawMetricCard(doc, MARGIN, wMetricY, cardW3, 'Cost', formatNumber(wMetrics.totalCost || 0));
    drawMetricCard(doc, MARGIN + cardW3 + 10, wMetricY, cardW3, 'Duration', `${wave.estimatedDurationMonths || 0} months`);
    drawMetricCard(doc, MARGIN + (cardW3 + 10) * 2, wMetricY, cardW3, 'Risk Delta',
      `${(wMetrics.riskDelta || 0) > 0 ? '+' : ''}${(wMetrics.riskDelta || 0).toFixed(0)}%`,
      (wMetrics.riskDelta || 0) < 0 ? '#22c55e' : '#ef4444');
    doc.y = wMetricY + 70;

    // Elements table
    const elements = wave.elements || [];
    if (elements.length > 0) {
      const elementRows = elements.map((el: any) => [
        el.name || '-',
        el.type || '-',
        `${el.currentStatus} → ${el.targetStatus}`,
        (el.riskScore || 0).toFixed(1),
        formatNumber(el.estimatedCost || 0),
      ]);
      drawTable(doc, ['Name', 'Type', 'Transition', 'Risk', 'Cost'],
        elementRows, [140, 90, 120, 50, 95], 'Transformation Roadmap');
    }

    // Recommendation
    if (wave.recommendation) {
      checkPageBreak(doc, 60);
      drawSectionTitle(doc, 'Recommendation');
      doc.font('Helvetica').fontSize(9).fillColor(DARK).text(wave.recommendation, MARGIN, doc.y, { width: CONTENT_W });
      doc.moveDown();
    }

    // Risk mitigations
    if (wave.riskMitigations && wave.riskMitigations.length > 0) {
      checkPageBreak(doc, 40);
      drawSectionTitle(doc, 'Risk Mitigations');
      for (const m of wave.riskMitigations) {
        doc.font('Helvetica').fontSize(9).fillColor(DARK).text(`• ${m}`, MARGIN + 10, doc.y, { width: CONTENT_W - 10 });
      }
      doc.moveDown();
    }
  }
}

// ─── Oracle Acceptance Risk Report ──────────────────────

const POSITION_COLORS: Record<string, string> = {
  approve: '#22c55e',
  reject: '#ef4444',
  modify: '#eab308',
  abstain: '#94a3b8',
};

async function renderOracleReport(
  doc: PDFKit.PDFDocument,
  project: { name: string } | null,
  assessmentId: string,
) {
  const assessment = await OracleAssessment.findById(assessmentId).lean();
  if (!assessment) throw new Error('Oracle assessment not found');

  const verdict = assessment.verdict as Record<string, unknown>;
  const proposal = assessment.proposal as Record<string, unknown>;
  const audit = verdict.auditReport as Record<string, unknown> | undefined;
  const agentVerdicts = (verdict.agentVerdicts || []) as Array<Record<string, unknown>>;
  const resistanceFactors = (verdict.resistanceFactors || []) as Array<Record<string, unknown>>;
  const mitigations = (verdict.mitigationSuggestions || []) as string[];
  const fatigue = verdict.fatigueForecast as Record<string, unknown> | undefined;

  const projectName = project?.name || 'Unknown Project';
  const ts = new Date(assessment.createdAt || verdict.timestamp as string).toISOString();

  // ─── KSU Classification (BSI IT-Grundschutz) ───
  currentClassification = KSU_LABEL;
  doc.info.Title = `Oracle Acceptance Risk Assessment — ${projectName}`;
  doc.info.Subject = KSU_LABEL;
  doc.info.Keywords = 'KSU C3, VERTRAULICH, BSI IT-Grundschutz, EU AI Act, Oracle Assessment';

  // ─── Page 1: Executive Summary ───
  drawHeader(doc, 'Oracle — Acceptance Risk Assessment', `${projectName} · ${ts.slice(0, 10)}`);
  drawClassificationBanner(doc);
  drawFooter(doc, 1, KSU_LABEL);

  // Score ring area
  const score = Number(verdict.acceptanceRiskScore) || 0;
  const riskLevel = String(verdict.riskLevel || 'unknown');
  const position = String(verdict.overallPosition || 'unknown');
  const riskColor = RISK_COLORS[riskLevel] || GRAY;

  doc.moveDown(0.5);
  drawSectionTitle(doc, 'Assessment Result');

  const cardY = doc.y;
  drawMetricCard(doc, MARGIN, cardY, 120, 'Risk Score', String(score), riskColor);
  drawMetricCard(doc, MARGIN + 130, cardY, 120, 'Risk Level', riskLevel.toUpperCase(), riskColor);
  drawMetricCard(doc, MARGIN + 260, cardY, 120, 'Position', position.replace(/_/g, ' '), riskColor);
  const durationMs = Number(verdict.durationMs) || 0;
  drawMetricCard(doc, MARGIN + 390, cardY, 105, 'Duration', `${(durationMs / 1000).toFixed(1)}s`);
  doc.y = cardY + 65;

  // Proposal details
  drawSectionTitle(doc, 'Proposal');
  doc.font('Helvetica-Bold').fontSize(11).fillColor(DARK).text(String(proposal.title || ''), MARGIN);
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(9).fillColor(GRAY);
  doc.text(`Change Type: ${String(proposal.changeType || '')}`, MARGIN);
  if (proposal.estimatedCost) doc.text(`Estimated Cost: $${Number(proposal.estimatedCost).toLocaleString()}`, MARGIN);
  if (proposal.estimatedDuration) doc.text(`Estimated Duration: ${proposal.estimatedDuration} months`, MARGIN);
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(9).fillColor(DARK).text(String(proposal.description || ''), MARGIN, doc.y, { width: CONTENT_W });
  doc.moveDown(0.8);

  // Affected elements table
  const affectedEls = (audit?.proposal as Record<string, unknown>)?.affectedElements as Array<Record<string, unknown>> | undefined;
  if (affectedEls && affectedEls.length > 0) {
    drawSectionTitle(doc, 'Affected Elements');
    drawTable(doc,
      ['Element', 'Type', 'Layer', 'Annual Cost', 'Maturity', 'Error %', 'TDR', 'Deps'],
      affectedEls.map((e) => [
        String(e.name || '').slice(0, 25),
        String(e.type || '').replace(/_/g, ' ').slice(0, 18),
        String(e.layer || ''),
        e.annualCost ? `$${Number(e.annualCost).toLocaleString()}` : '—',
        e.maturityLevel ? `${e.maturityLevel}/5` : '—',
        e.errorRatePercent ? `${e.errorRatePercent}%` : '—',
        e.technicalDebtRatio ? `${(Number(e.technicalDebtRatio) * 100).toFixed(0)}%` : '—',
        `${e.dependencyCount || 0}↗ ${e.dependentCount || 0}↙`,
      ]),
      [130, 90, 55, 60, 40, 40, 35, 45],
      'Affected Elements',
    );
    doc.moveDown(0.8);
  }

  // ─── Page 2: Stakeholder Verdicts ───
  addNewPage(doc, 'Oracle — Stakeholder Verdicts', `${projectName} · ${ts.slice(0, 10)}`, KSU_LABEL);

  drawSectionTitle(doc, 'Stakeholder Verdict Summary');

  // Summary table
  const agentReports = (audit?.agentReports || agentVerdicts) as Array<Record<string, unknown>>;
  drawTable(doc,
    ['Persona', 'Position', 'Score', 'Weight', 'Risk Contrib.', 'Threshold', 'Priorities'],
    agentReports.map((a) => [
      String(a.personaName || '').slice(0, 20),
      String(a.position || ''),
      String(a.acceptanceScore || ''),
      ((Number(a.weight) || 0) * 100).toFixed(0) + '%',
      String(a.weightedRiskContribution || '—'),
      String(a.riskThreshold || '—'),
      Array.isArray(a.priorities) ? a.priorities.map((p: string) => p.replace(/_/g, ' ')).join(', ').slice(0, 30) : '—',
    ]),
    [100, 50, 40, 40, 60, 55, 150],
    'Stakeholder Summary',
  );
  doc.moveDown(1);

  // Detailed verdicts
  drawSectionTitle(doc, 'Detailed Stakeholder Reasoning');

  for (const agent of agentReports) {
    checkPageBreak(doc, 100);
    const posColor = POSITION_COLORS[String(agent.position)] || GRAY;

    doc.font('Helvetica-Bold').fontSize(10).fillColor(posColor)
      .text(`${agent.personaName} — ${String(agent.position).toUpperCase()} (Score: ${agent.acceptanceScore})`, MARGIN);
    doc.moveDown(0.2);

    // Context box
    if (agent.riskThreshold || agent.budgetConstraint) {
      doc.font('Helvetica').fontSize(7).fillColor(GRAY);
      const ctx = [
        agent.riskThreshold ? `Risk threshold: ${agent.riskThreshold}` : '',
        agent.budgetConstraint ? `Budget: $${Number(agent.budgetConstraint).toLocaleString()}` : '',
        agent.expectedCapacity ? `Capacity: ${agent.expectedCapacity} parallel` : '',
        Array.isArray(agent.visibleLayers) ? `Layers: ${(agent.visibleLayers as string[]).join(', ')}` : '',
      ].filter(Boolean).join(' | ');
      doc.text(ctx, MARGIN);
      doc.moveDown(0.2);
    }

    doc.font('Helvetica').fontSize(9).fillColor(DARK)
      .text(String(agent.reasoning || ''), MARGIN, doc.y, { width: CONTENT_W });
    doc.moveDown(0.2);

    const concerns = (agent.concerns || []) as string[];
    if (concerns.length > 0) {
      doc.font('Helvetica').fontSize(8).fillColor(GRAY);
      for (const c of concerns) {
        doc.text(`  ⚠ ${c}`, MARGIN, doc.y, { width: CONTENT_W - 10 });
      }
    }
    doc.moveDown(0.6);
  }

  // ─── Page 3: Resistance, Mitigations, Scoring ───
  addNewPage(doc, 'Oracle — Risk Analysis & Compliance', `${projectName} · ${ts.slice(0, 10)}`, KSU_LABEL);

  // Resistance Factors
  if (resistanceFactors.length > 0) {
    drawSectionTitle(doc, 'Resistance Factors');
    drawTable(doc,
      ['Factor', 'Severity', 'Source'],
      resistanceFactors.map((f) => [
        String(f.factor || '').slice(0, 55),
        String(f.severity || ''),
        String(f.source || ''),
      ]),
      [300, 60, 135],
      'Resistance Factors',
    );
    doc.moveDown(0.8);
  }

  // Mitigation Suggestions
  if (mitigations.length > 0) {
    drawSectionTitle(doc, 'Mitigation Suggestions');
    doc.font('Helvetica').fontSize(9).fillColor(DARK);
    mitigations.forEach((m, i) => {
      checkPageBreak(doc, 20);
      doc.text(`${i + 1}. ${m}`, MARGIN, doc.y, { width: CONTENT_W });
      doc.moveDown(0.3);
    });
    doc.moveDown(0.5);
  }

  // Fatigue Forecast
  if (fatigue) {
    drawSectionTitle(doc, 'Fatigue Forecast');
    const fY = doc.y;
    drawMetricCard(doc, MARGIN, fY, 160, 'Projected Delay', `${fatigue.projectedDelayMonths || 0} months`);
    drawMetricCard(doc, MARGIN + 170, fY, 160, 'Budget at Risk', `$${Number(fatigue.budgetAtRisk || 0).toLocaleString()}`);
    const overloaded = (fatigue.overloadedStakeholders || []) as string[];
    drawMetricCard(doc, MARGIN + 340, fY, 155, 'Overloaded Stakeholders', overloaded.length > 0 ? overloaded.join(', ') : 'None');
    doc.y = fY + 65;
    doc.moveDown(0.5);
  }

  // Scoring Methodology
  drawSectionTitle(doc, 'Scoring Methodology (Compliance)');
  const scoring = audit?.scoring as Record<string, unknown> | undefined;
  doc.font('Helvetica').fontSize(9).fillColor(DARK);
  doc.text(`Method: Weighted Stakeholder Average`, MARGIN);
  doc.text('Formula: Risk Score = SUM( (100 - acceptance_score_i) * weight_i ) / SUM( weight_i )', MARGIN);
  doc.moveDown(0.3);

  if (scoring?.weights) {
    const weights = scoring.weights as Record<string, number>;
    doc.font('Helvetica').fontSize(8).fillColor(GRAY);
    doc.text('Stakeholder Weights:', MARGIN);
    for (const [role, w] of Object.entries(weights)) {
      doc.text(`  ${role.replace(/_/g, ' ')}: ${(w * 100).toFixed(0)}%`, MARGIN);
    }
    doc.moveDown(0.3);
  }

  doc.font('Helvetica').fontSize(8).fillColor(GRAY);
  doc.text('Risk Level Thresholds: Low < 30 | Medium 30-59 | High 60-79 | Critical >= 80', MARGIN);
  doc.text('Position Thresholds: Likely Accepted < 35 | Contested 35-64 | Likely Rejected >= 65', MARGIN);
  doc.moveDown(0.5);

  // Audit metadata
  drawSectionTitle(doc, 'Audit Metadata');
  doc.font('Helvetica').fontSize(8).fillColor(GRAY);
  doc.text(`Assessment ID: ${audit?.assessmentId || assessment._id}`, MARGIN);
  doc.text(`Timestamp: ${ts}`, MARGIN);
  doc.text(`LLM Provider: ${audit?.provider || 'unknown'}`, MARGIN);
  doc.text(`Model: ${audit?.model || 'unknown'}`, MARGIN);
  doc.text(`Project: ${projectName}`, MARGIN);

  // ─── Page 4: EU AI Act Compliance & Decision Trace ───
  addNewPage(doc, 'Oracle — EU AI Act Compliance Audit Trail', `${projectName} · ${ts.slice(0, 10)}`, KSU_LABEL);

  // System Risk Classification (Art. 6-7)
  const riskClass = audit?.systemRiskClassification as Record<string, unknown> | undefined;
  drawSectionTitle(doc, 'System Risk Classification (EU AI Act Art. 6-7)');
  doc.font('Helvetica').fontSize(9).fillColor(DARK);
  doc.text(`Classification Level: ${riskClass?.euAiActLevel || 'limited'}`, MARGIN);
  doc.text(`Human Oversight Required: ${riskClass?.humanOversightRequired !== false ? 'Yes' : 'No'}`, MARGIN);
  doc.text(`Legal Reference: ${riskClass?.articleReference || 'EU AI Act 2024/1689, Art. 6(2), Art. 52(1)'}`, MARGIN);
  doc.moveDown(0.3);
  doc.font('Helvetica').fontSize(8).fillColor(GRAY);
  doc.text(String(riskClass?.justification || 'AI-assisted decision support — provides recommendations to human decision-makers.'), MARGIN, doc.y, { width: CONTENT_W });
  doc.moveDown(0.8);

  // Human Oversight Status (Art. 14)
  const oversight = audit?.humanOversight as Record<string, unknown> | undefined;
  drawSectionTitle(doc, 'Human Oversight Status (EU AI Act Art. 14)');
  const oversightStatus = String(oversight?.status || 'pending_review').replace(/_/g, ' ').toUpperCase();
  const oversightColor = oversight?.status === 'approved' ? '#22c55e' : oversight?.status === 'rejected' ? '#ef4444' : '#eab308';
  doc.font('Helvetica-Bold').fontSize(10).fillColor(oversightColor).text(oversightStatus, MARGIN);
  doc.font('Helvetica').fontSize(8).fillColor(GRAY);
  if (oversight?.reviewedBy) doc.text(`Reviewed by: ${oversight.reviewedBy}`, MARGIN);
  if (oversight?.reviewedAt) doc.text(`Reviewed at: ${oversight.reviewedAt}`, MARGIN);
  if (oversight?.notes) doc.text(`Notes: ${oversight.notes}`, MARGIN);
  doc.moveDown(0.8);

  // Initiator Identity (Art. 12)
  const initiator = audit?.initiator as Record<string, unknown> | undefined;
  drawSectionTitle(doc, 'Assessment Initiator (EU AI Act Art. 12)');
  doc.font('Helvetica').fontSize(9).fillColor(DARK);
  if (initiator?.userName) {
    doc.text(`User: ${initiator.userName}`, MARGIN);
    doc.text(`Email: ${initiator.userEmail}`, MARGIN);
    doc.text(`User ID: ${initiator.userId}`, MARGIN);
    doc.text(`Auth Method: ${String(initiator.authMethod || 'unknown').replace(/_/g, ' ')}`, MARGIN);
    if (initiator.apiKeyPrefix) doc.text(`API Key Hash Prefix: ${initiator.apiKeyPrefix}...`, MARGIN);
  } else {
    doc.text(`User ID: ${assessment.userId || 'unknown'}`, MARGIN);
    doc.text('Detailed initiator info not available (assessment predates v2.0)', MARGIN);
  }
  doc.moveDown(0.8);

  // Context Snapshot (Jasper Principle)
  const ctx = audit?.contextSnapshot as Record<string, unknown> | undefined;
  drawSectionTitle(doc, 'Architecture Context Snapshot');
  doc.font('Helvetica').fontSize(9).fillColor(DARK);
  if (ctx) {
    doc.text(`Snapshot ID: ${ctx.id}`, MARGIN);
    doc.text(`Captured at: ${ctx.timestamp}`, MARGIN);
    doc.text(`Total Elements in Project: ${ctx.elementCount}`, MARGIN);
    doc.text(`Total Connections in Project: ${ctx.connectionCount}`, MARGIN);
    doc.text(`Affected Elements: ${ctx.affectedElementCount}`, MARGIN);
  } else {
    doc.text('Context snapshot not available (assessment predates v2.0)', MARGIN);
  }
  doc.moveDown(0.8);

  // Per-Agent Decision Traces (Art. 13-14) — Summary
  drawSectionTitle(doc, 'Per-Agent Decision Traces (EU AI Act Art. 13-14)');
  doc.font('Helvetica').fontSize(8).fillColor(GRAY);
  doc.text('Each agent received a filtered view of the architecture and a tailored system prompt.', MARGIN);
  doc.text('Full system prompts and raw LLM responses follow on subsequent pages.', MARGIN);
  doc.moveDown(0.5);

  for (const agent of agentReports) {
    checkPageBreak(doc, 80);
    const posColor = POSITION_COLORS[String(agent.position)] || GRAY;
    const mp = agent.modelParams as Record<string, unknown> | undefined;

    doc.font('Helvetica-Bold').fontSize(9).fillColor(posColor)
      .text(`${agent.personaName} — ${String(agent.position).toUpperCase()}`, MARGIN);
    doc.moveDown(0.15);

    doc.font('Helvetica').fontSize(7).fillColor(GRAY);
    const traceInfo = [
      mp ? `Provider: ${mp.actualProvider || mp.provider}` : null,
      mp ? `Model: ${mp.model}` : null,
      mp ? `Temperature: ${mp.temperature}` : null,
      mp ? `Max Tokens: ${mp.maxTokens}` : null,
      mp?.fallbackUsed ? `FALLBACK USED (primary: ${mp.provider})` : null,
    ].filter(Boolean).join(' | ');
    if (traceInfo) doc.text(traceInfo, MARGIN);

    const promptLen = String(agent.systemPrompt || '').length;
    const responseLen = String(agent.rawResponse || '').length;
    const contextLen = String(agent.architectureContext || '').length;
    doc.text(`Prompt: ${promptLen} chars | Response: ${responseLen} chars | Context: ${contextLen} chars`, MARGIN);
    doc.moveDown(0.4);
  }

  // ─── Full Agent System Prompts (Art. 13: Transparency) ───
  for (const agent of agentReports) {
    const promptText = String(agent.systemPrompt || '');
    const responseText = String(agent.rawResponse || '');
    if (!promptText) continue;

    addNewPage(doc, `Oracle — System Prompt: ${String(agent.personaName || '').slice(0, 30)}`, `${projectName} · ${ts.slice(0, 10)}`, KSU_LABEL);

    const posColor = POSITION_COLORS[String(agent.position)] || GRAY;
    doc.font('Helvetica-Bold').fontSize(10).fillColor(posColor)
      .text(`${agent.personaName} — System Prompt`, MARGIN);
    doc.moveDown(0.3);

    // Prompt text in small monospace-style font with auto page breaks
    doc.font('Helvetica').fontSize(7).fillColor(DARK);
    doc.text(promptText, MARGIN, doc.y, { width: CONTENT_W });
    doc.moveDown(0.8);

    // Raw LLM Response
    checkPageBreak(doc, 60);
    doc.font('Helvetica-Bold').fontSize(9).fillColor(posColor)
      .text(`${agent.personaName} — Raw LLM Response`, MARGIN);
    doc.moveDown(0.3);

    doc.save();
    const responseBoxY = doc.y;
    doc.roundedRect(MARGIN, responseBoxY, CONTENT_W, 2, 1).fill('#f0fdf4');
    doc.restore();

    doc.font('Helvetica').fontSize(7).fillColor(DARK);
    doc.text(responseText, MARGIN + 5, doc.y, { width: CONTENT_W - 10 });
    doc.moveDown(0.5);
  }

  // Compliance Footer
  checkPageBreak(doc, 60);
  doc.font('Helvetica').fontSize(7).fillColor(GRAY);
  doc.moveTo(MARGIN, doc.y).lineTo(PAGE_W - MARGIN, doc.y).strokeColor(GRAY).lineWidth(0.5).stroke();
  doc.moveDown(0.3);
  doc.moveDown(0.2);
  doc.text('This report complies with EU AI Act 2024/1689 transparency obligations (Art. 13, 52) and', MARGIN);
  doc.text('EU Data Act 2023/2854 data provenance requirements. Full decision traces including system', MARGIN);
  doc.text('prompts, raw LLM responses, and filtered architecture context are included in this document.', MARGIN);
  doc.moveDown(0.2);
  doc.text('Schema version: oracle_acceptance_risk_assessment v2.0', MARGIN);
  doc.moveDown(0.2);
  doc.font('Helvetica-Bold').fontSize(7).fillColor('#7f1d1d');
  doc.text(`Dokumentenklassifikation: ${KSU_FULL}`, MARGIN);
  currentClassification = undefined; // reset for non-oracle reports
}

// ─── Main Export ─────────────────────────────────────────

export type ReportType = 'executive' | 'simulation' | 'inventory' | 'roadmap' | 'oracle';

export async function generateReport(
  projectId: string,
  type: ReportType,
  options?: { runId?: string; roadmapId?: string; assessmentId?: string }
): Promise<PDFKit.PDFDocument> {
  const project = await Project.findById(projectId).lean();
  if (!project) throw new Error('Project not found');

  currentPage = 1;

  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 50, left: 50, right: 50 },
    info: {
      Title: `TheArchitect — ${type.charAt(0).toUpperCase() + type.slice(1)} Report`,
      Author: 'TheArchitect',
      Subject: project.name,
    },
  });

  switch (type) {
    case 'executive':
      await renderExecutiveReport(doc, project, projectId);
      break;
    case 'simulation': {
      if (!options?.runId) throw new Error('runId is required for simulation reports');
      const run = await SimulationRun.findById(options.runId).lean();
      if (!run) throw new Error('Simulation run not found');
      await renderSimulationReport(doc, project, run as unknown as Record<string, unknown>);
      break;
    }
    case 'inventory':
      await renderInventoryReport(doc, project, projectId);
      break;
    case 'roadmap': {
      if (!options?.roadmapId) throw new Error('roadmapId is required for roadmap reports');
      await renderRoadmapReport(doc, project, options.roadmapId);
      break;
    }
    case 'oracle': {
      if (!options?.assessmentId) throw new Error('assessmentId is required for oracle reports');
      await renderOracleReport(doc, project, options.assessmentId);
      break;
    }
    default:
      throw new Error(`Unknown report type: ${type}`);
  }

  doc.end();
  return doc;
}
