import PDFDocument from 'pdfkit';
import { Project } from '../models/Project';
import { SimulationRun } from '../models/SimulationRun';
import { getXRaySummary, XRaySummary } from './xray.service';
import { assessRisk, estimateCosts, RiskAssessment } from './analytics.service';
import { checkCompliance, ComplianceReport } from './compliance.service';
import { runCypher } from '../config/neo4j';
import { TransformationRoadmap } from '../models/TransformationRoadmap';

// ─── Colors ──────────────────────────────────────────────
const ACCENT = '#00ff41';
const DARK = '#0a0a0a';
const GRAY = '#4a5a4a';
const LIGHT_GRAY = '#d0d0d0';
const WHITE = '#ffffff';
const RISK_COLORS: Record<string, string> = {
  critical: '#ef4444',
  high: '#f97316',
  medium: '#eab308',
  low: '#22c55e',
};
const RATING_COLORS: Record<string, string> = {
  green: '#22c55e',
  yellow: '#eab308',
  orange: '#f97316',
  red: '#ef4444',
};

// ─── Layout ──────────────────────────────────────────────
const PAGE_W = 595.28;
const MARGIN = 50;
const CONTENT_W = PAGE_W - MARGIN * 2;

// ─── Shared Helpers ──────────────────────────────────────

function drawHeader(doc: PDFKit.PDFDocument, title: string, subtitle?: string) {
  doc.save();
  doc.rect(0, 0, PAGE_W, 70).fill(DARK);
  doc.rect(0, 68, PAGE_W, 3).fill(ACCENT);
  doc.font('Helvetica-Bold').fontSize(18).fillColor(WHITE).text('TheArchitect', MARGIN, 20);
  doc.font('Helvetica').fontSize(10).fillColor(LIGHT_GRAY).text(title, MARGIN, 44);
  if (subtitle) {
    doc.font('Helvetica').fontSize(8).fillColor(GRAY).text(subtitle, PAGE_W - MARGIN - 200, 44, { width: 200, align: 'right' });
  }
  doc.restore();
  doc.y = 90;
}

function drawFooter(doc: PDFKit.PDFDocument, pageNum: number) {
  const y = 800;
  doc.save();
  doc.moveTo(MARGIN, y).lineTo(PAGE_W - MARGIN, y).strokeColor(LIGHT_GRAY).lineWidth(0.5).stroke();
  doc.font('Helvetica').fontSize(7).fillColor(GRAY);
  doc.text('Confidential — Generated by TheArchitect', MARGIN, y + 6);
  doc.text(`Page ${pageNum}`, PAGE_W - MARGIN - 50, y + 6, { width: 50, align: 'right' });
  doc.restore();
}

function drawSectionTitle(doc: PDFKit.PDFDocument, title: string) {
  checkPageBreak(doc, 40);
  doc.font('Helvetica-Bold').fontSize(12).fillColor(DARK).text(title, MARGIN, doc.y);
  doc.moveTo(MARGIN, doc.y + 2).lineTo(MARGIN + CONTENT_W, doc.y + 2).strokeColor(ACCENT).lineWidth(1).stroke();
  doc.moveDown(0.8);
}

function drawMetricCard(doc: PDFKit.PDFDocument, x: number, y: number, w: number, label: string, value: string, color?: string) {
  doc.save();
  doc.roundedRect(x, y, w, 50, 4).fillAndStroke('#f8fafc', LIGHT_GRAY);
  doc.font('Helvetica-Bold').fontSize(16).fillColor(color || DARK).text(value, x + 8, y + 8, { width: w - 16 });
  doc.font('Helvetica').fontSize(8).fillColor(GRAY).text(label, x + 8, y + 32, { width: w - 16 });
  doc.restore();
}

function drawRiskBadge(doc: PDFKit.PDFDocument, x: number, y: number, level: string) {
  const color = RISK_COLORS[level] || GRAY;
  doc.save();
  doc.circle(x + 4, y + 4, 4).fill(color);
  doc.font('Helvetica').fontSize(8).fillColor(DARK).text(level, x + 12, y, { width: 50 });
  doc.restore();
}

let currentPage = 1;

function addNewPage(doc: PDFKit.PDFDocument, title: string, subtitle?: string) {
  doc.addPage();
  currentPage++;
  drawHeader(doc, title, subtitle);
  drawFooter(doc, currentPage);
}

function checkPageBreak(doc: PDFKit.PDFDocument, neededHeight: number = 60) {
  if (doc.y + neededHeight > 780) {
    addNewPage(doc, '', '');
    return true;
  }
  return false;
}

function drawTable(
  doc: PDFKit.PDFDocument,
  headers: string[],
  rows: string[][],
  colWidths: number[],
  title: string
) {
  const rowHeight = 18;
  const headerHeight = 22;
  let y = doc.y;

  // Header
  checkPageBreak(doc, headerHeight + rowHeight * 2);
  y = doc.y;
  doc.save();
  doc.rect(MARGIN, y, CONTENT_W, headerHeight).fill(DARK);
  let x = MARGIN;
  doc.font('Helvetica-Bold').fontSize(8).fillColor(WHITE);
  for (let i = 0; i < headers.length; i++) {
    doc.text(headers[i], x + 4, y + 6, { width: colWidths[i] - 8 });
    x += colWidths[i];
  }
  doc.restore();
  y += headerHeight;

  // Rows
  for (let r = 0; r < rows.length; r++) {
    if (y + rowHeight > 780) {
      addNewPage(doc, title, '');
      y = doc.y;
      // Re-draw header
      doc.save();
      doc.rect(MARGIN, y, CONTENT_W, headerHeight).fill(DARK);
      x = MARGIN;
      doc.font('Helvetica-Bold').fontSize(8).fillColor(WHITE);
      for (let i = 0; i < headers.length; i++) {
        doc.text(headers[i], x + 4, y + 6, { width: colWidths[i] - 8 });
        x += colWidths[i];
      }
      doc.restore();
      y += headerHeight;
    }

    if (r % 2 === 0) {
      doc.save();
      doc.rect(MARGIN, y, CONTENT_W, rowHeight).fill('#f8fafc');
      doc.restore();
    }
    x = MARGIN;
    doc.font('Helvetica').fontSize(8).fillColor(DARK);
    for (let i = 0; i < rows[r].length; i++) {
      doc.text(rows[r][i] || '-', x + 4, y + 5, { width: colWidths[i] - 8 });
      x += colWidths[i];
    }
    y += rowHeight;
  }

  doc.y = y + 10;
}

function drawBarChart(doc: PDFKit.PDFDocument, x: number, y: number, w: number, data: { label: string; value: number; color?: string }[]) {
  const barH = 14;
  const gap = 6;
  const maxVal = Math.max(...data.map((d) => d.value), 1);
  const labelW = 100;
  const barW = w - labelW - 50;

  for (let i = 0; i < data.length; i++) {
    const by = y + i * (barH + gap);
    doc.font('Helvetica').fontSize(8).fillColor(DARK).text(data[i].label, x, by + 2, { width: labelW });
    const fillW = (data[i].value / maxVal) * barW;
    doc.save();
    doc.roundedRect(x + labelW, by, barW, barH, 2).fill('#e2e8f0');
    if (fillW > 0) {
      doc.roundedRect(x + labelW, by, Math.max(fillW, 4), barH, 2).fill(data[i].color || ACCENT);
    }
    doc.restore();
    doc.font('Helvetica').fontSize(8).fillColor(DARK).text(formatNumber(data[i].value), x + labelW + barW + 4, by + 2);
  }

  doc.y = y + data.length * (barH + gap) + 10;
}

function formatNumber(n: number): string {
  if (n >= 1_000_000) return `€${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `€${(n / 1_000).toFixed(0)}K`;
  return `€${n}`;
}

function formatPercent(n: number): string {
  return `${Math.round(n)}%`;
}

// ─── Executive Report ────────────────────────────────────

async function renderExecutiveReport(doc: PDFKit.PDFDocument, project: { name: string; description?: string }, projectId: string) {
  const subtitle = `Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`;
  drawHeader(doc, `Executive Summary — ${project.name}`, subtitle);
  drawFooter(doc, 1);

  let xray: XRaySummary;
  let compliance: ComplianceReport;
  try {
    [xray, compliance] = await Promise.all([
      getXRaySummary(projectId),
      checkCompliance(projectId),
    ]);
  } catch {
    doc.font('Helvetica').fontSize(10).fillColor(DARK).text('No architecture elements found. Import elements to generate a report.', MARGIN, doc.y);
    return;
  }

  // Key Metrics (2x2 grid)
  drawSectionTitle(doc, 'Key Metrics');
  const metricY = doc.y;
  const cardW = (CONTENT_W - 10) / 2;
  drawMetricCard(doc, MARGIN, metricY, cardW, 'Total Risk Exposure', formatNumber(xray.metrics.totalRiskExposure), '#ef4444');
  drawMetricCard(doc, MARGIN + cardW + 10, metricY, cardW, 'Transformation Progress', formatPercent(xray.metrics.transformationProgress), ACCENT);
  drawMetricCard(doc, MARGIN, metricY + 60, cardW, 'Time to Target', `${xray.metrics.timeToTarget} months`);
  drawMetricCard(doc, MARGIN + cardW + 10, metricY + 60, cardW, 'Decision Confidence', formatPercent(xray.metrics.decisionConfidence), '#22c55e');
  doc.y = metricY + 130;

  // Top Risk Elements
  drawSectionTitle(doc, 'Top Risk Elements');
  const riskRows = xray.riskElements.slice(0, 10).map((e) => [
    e.name,
    e.type,
    e.riskScore.toFixed(1),
    e.riskScore >= 7 ? 'critical' : e.riskScore >= 5 ? 'high' : e.riskScore >= 3 ? 'medium' : 'low',
  ]);
  if (riskRows.length > 0) {
    drawTable(doc, ['Name', 'Type', 'Score', 'Risk Level'], riskRows, [180, 120, 60, 80], 'Executive Summary');
  } else {
    doc.font('Helvetica').fontSize(9).fillColor(GRAY).text('No risk elements found.', MARGIN, doc.y);
    doc.moveDown();
  }

  // Page 2: Cost + Compliance
  addNewPage(doc, `Executive Summary — ${project.name}`, subtitle);

  // Cost Overview
  drawSectionTitle(doc, 'Cost Overview');
  const costY = doc.y;
  drawMetricCard(doc, MARGIN, costY, cardW, 'Total TCO', formatNumber(xray.costSummary.totalCost));
  drawMetricCard(doc, MARGIN + cardW + 10, costY, cardW, 'Optimization Potential', formatNumber(xray.costSummary.optimizationTotal), '#22c55e');
  doc.y = costY + 70;

  // Cost by Category
  const categories = Object.entries(xray.costSummary.byCategory);
  if (categories.length > 0) {
    drawSectionTitle(doc, 'Cost by Category');
    drawBarChart(doc, MARGIN, doc.y, CONTENT_W, categories.map(([label, value]) => ({ label, value })));
  }

  // Compliance
  drawSectionTitle(doc, 'Compliance');
  const compY = doc.y;
  const scoreColor = compliance.summary.complianceScore >= 80 ? '#22c55e' : compliance.summary.complianceScore >= 50 ? '#eab308' : '#ef4444';
  drawMetricCard(doc, MARGIN, compY, cardW, 'Compliance Score', formatPercent(compliance.summary.complianceScore), scoreColor);
  drawMetricCard(doc, MARGIN + cardW + 10, compY, cardW, 'Violations',
    `${compliance.summary.errors} errors, ${compliance.summary.warnings} warnings`);
  doc.y = compY + 70;

  if (compliance.violations.length > 0) {
    const violationRows = compliance.violations.slice(0, 15).map((v) => [
      v.elementName,
      v.severity,
      v.policyName,
      v.message.slice(0, 60),
    ]);
    drawTable(doc, ['Element', 'Severity', 'Policy', 'Message'], violationRows, [120, 60, 120, 195], 'Executive Summary');
  }
}

// ─── Simulation Report ───────────────────────────────────

async function renderSimulationReport(doc: PDFKit.PDFDocument, project: { name: string }, run: Record<string, unknown>) {
  const result = run.result as Record<string, unknown> | undefined;
  const config = run.config as Record<string, unknown> | undefined;
  const subtitle = `Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`;

  drawHeader(doc, `MiroFish Simulation — ${project.name}`, subtitle);
  drawFooter(doc, 1);

  // Scenario Info
  drawSectionTitle(doc, 'Scenario Overview');
  doc.font('Helvetica').fontSize(9).fillColor(DARK);
  doc.text(`Simulation: ${run.name || 'Unnamed'}`, MARGIN, doc.y);
  doc.text(`Scenario Type: ${run.scenarioType || '-'}`, MARGIN, doc.y);
  doc.text(`Status: ${run.status || '-'}`, MARGIN, doc.y);
  if (config) {
    doc.text(`Description: ${(config as Record<string, unknown>).scenarioDescription || '-'}`, MARGIN, doc.y);
    doc.text(`Max Rounds: ${(config as Record<string, unknown>).maxRounds || '-'}`, MARGIN, doc.y);
  }
  doc.moveDown();

  if (!result) {
    doc.font('Helvetica').fontSize(10).fillColor(GRAY).text('Simulation has not completed yet.', MARGIN, doc.y);
    return;
  }

  // Outcome
  drawSectionTitle(doc, 'Outcome');
  doc.font('Helvetica-Bold').fontSize(11).fillColor(DARK).text(`${(result.outcome as string || 'unknown').toUpperCase()}`, MARGIN, doc.y);
  doc.moveDown(0.3);
  if (result.summary) {
    doc.font('Helvetica').fontSize(9).fillColor(DARK).text(result.summary as string, MARGIN, doc.y, { width: CONTENT_W });
  }
  doc.moveDown();

  // Fatigue Scorecard
  const fatigue = result.fatigue as Record<string, unknown> | undefined;
  if (fatigue) {
    drawSectionTitle(doc, 'Fatigue Scorecard');
    const fatigueY = doc.y;
    const cardW3 = (CONTENT_W - 20) / 3;
    const rating = (fatigue.rating as string) || 'green';
    const ratingColor = RATING_COLORS[rating] || GRAY;
    drawMetricCard(doc, MARGIN, fatigueY, cardW3, 'Fatigue Index', `${Math.round((fatigue.globalIndex as number || 0) * 100)}%`, ratingColor);
    drawMetricCard(doc, MARGIN + cardW3 + 10, fatigueY, cardW3, 'Projected Delay', `+${fatigue.totalProjectedDelayMonths || 0} months`, '#f97316');
    drawMetricCard(doc, MARGIN + (cardW3 + 10) * 2, fatigueY, cardW3, 'Budget at Risk', formatNumber((fatigue.budgetAtRisk as number) || 0), '#ef4444');
    doc.y = fatigueY + 70;

    // Recommendation
    if (fatigue.recommendation) {
      drawSectionTitle(doc, 'Recommendation');
      doc.font('Helvetica').fontSize(9).fillColor(DARK).text(fatigue.recommendation as string, MARGIN, doc.y, { width: CONTENT_W });
      doc.moveDown();
    }

    // Per-Agent Fatigue
    const perAgent = fatigue.perAgent as Array<Record<string, unknown>> | undefined;
    if (perAgent && perAgent.length > 0) {
      addNewPage(doc, `MiroFish Simulation — ${project.name}`, subtitle);
      drawSectionTitle(doc, 'Stakeholder Fatigue Analysis');

      const agentRows = perAgent.map((a) => [
        a.agentName as string || '-',
        `${Math.round((a.fatigueIndex as number || 0) * 100)}%`,
        `${Math.round((a.concurrencyLoad as number || 0) * 100)}%`,
        `${Math.round((a.negotiationDrag as number || 0) * 100)}%`,
        `${Math.round((a.constraintPressure as number || 0) * 100)}%`,
        a.projectedDelayMonths ? `+${a.projectedDelayMonths}m` : '-',
      ]);
      drawTable(doc, ['Agent', 'Fatigue', 'Concurrency', 'Negotiation', 'Constraint', 'Delay'],
        agentRows, [120, 70, 75, 80, 75, 75], 'Simulation Report');
    }

    // Bottleneck Elements
    const perElement = fatigue.perElement as Array<Record<string, unknown>> | undefined;
    if (perElement && perElement.length > 0) {
      drawSectionTitle(doc, 'Bottleneck Elements');
      const elementRows = perElement.slice(0, 10).map((e) => [
        e.elementName as string || '-',
        `${Math.round((e.negotiationDrag as number || 0) * 100)}%`,
        `${e.conflictRounds || 0}`,
        ((e.involvedAgents as string[]) || []).join(', '),
        e.projectedDelayMonths ? `+${e.projectedDelayMonths}m` : '-',
      ]);
      drawTable(doc, ['Element', 'Negotiation', 'Conflicts', 'Agents', 'Delay'],
        elementRows, [140, 75, 65, 140, 75], 'Simulation Report');
    }
  }

  // Emergence Metrics
  const emergence = result.emergenceMetrics as Record<string, unknown> | undefined;
  if (emergence) {
    checkPageBreak(doc, 100);
    drawSectionTitle(doc, 'Emergence Metrics');
    const emY = doc.y;
    const cardW4 = (CONTENT_W - 30) / 4;
    drawMetricCard(doc, MARGIN, emY, cardW4, 'Consensus Score', formatPercent((emergence.consensusScore as number || 0) * 100));
    drawMetricCard(doc, MARGIN + cardW4 + 10, emY, cardW4, 'Deadlocks', `${emergence.deadlockCount || 0}`);
    drawMetricCard(doc, MARGIN + (cardW4 + 10) * 2, emY, cardW4, 'Avg Rounds', `${(emergence.avgRoundsToConsensus as number || 0).toFixed(1)}`);
    drawMetricCard(doc, MARGIN + (cardW4 + 10) * 3, emY, cardW4, 'Hallucinations Blocked', `${emergence.blockedHallucinations || 0}`);
    doc.y = emY + 70;
  }
}

// ─── Inventory Report ────────────────────────────────────

async function renderInventoryReport(doc: PDFKit.PDFDocument, project: { name: string }, projectId: string) {
  const subtitle = `Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`;
  drawHeader(doc, `Architecture Inventory — ${project.name}`, subtitle);
  drawFooter(doc, 1);

  // Fetch elements from Neo4j
  const records = await runCypher(
    `MATCH (e:ArchitectureElement {projectId: $projectId})
     RETURN e.id as id, e.name as name, e.type as type, e.layer as layer,
            e.status as status, e.riskLevel as riskLevel,
            e.maturityLevel as maturity, e.togafDomain as domain
     ORDER BY e.layer, e.riskLevel DESC`,
    { projectId }
  );

  interface ElementRow {
    name: string;
    type: string;
    layer: string;
    status: string;
    riskLevel: string;
    maturity: number;
    domain: string;
  }

  const elements: ElementRow[] = records.map((r) => ({
    name: r.get('name') || '-',
    type: r.get('type') || '-',
    layer: r.get('layer') || '-',
    status: r.get('status') || '-',
    riskLevel: r.get('riskLevel') || 'low',
    maturity: r.get('maturity')?.toNumber?.() || r.get('maturity') || 3,
    domain: r.get('domain') || '-',
  }));

  if (elements.length === 0) {
    doc.font('Helvetica').fontSize(10).fillColor(DARK).text('No architecture elements found. Import elements to generate an inventory.', MARGIN, doc.y);
    return;
  }

  // Summary metrics
  drawSectionTitle(doc, 'Summary');
  const layers = ['strategy', 'business', 'information', 'application', 'technology'];
  const layerCounts = layers.map((l) => ({ label: l, value: elements.filter((e) => e.layer === l).length }));
  const avgMaturity = elements.reduce((s, e) => s + e.maturity, 0) / elements.length;
  const riskCounts = { critical: 0, high: 0, medium: 0, low: 0 };
  for (const e of elements) {
    const key = e.riskLevel as keyof typeof riskCounts;
    if (key in riskCounts) riskCounts[key]++;
  }

  const summaryY = doc.y;
  const cardW3 = (CONTENT_W - 20) / 3;
  drawMetricCard(doc, MARGIN, summaryY, cardW3, 'Total Elements', `${elements.length}`);
  drawMetricCard(doc, MARGIN + cardW3 + 10, summaryY, cardW3, 'Avg Maturity', avgMaturity.toFixed(1));
  drawMetricCard(doc, MARGIN + (cardW3 + 10) * 2, summaryY, cardW3, 'Critical/High Risk', `${riskCounts.critical + riskCounts.high}`, '#ef4444');
  doc.y = summaryY + 70;

  // Elements by Layer chart
  drawSectionTitle(doc, 'Elements by Layer');
  drawBarChart(doc, MARGIN, doc.y, CONTENT_W, layerCounts.filter((l) => l.value > 0).map((l) => ({
    label: l.label.charAt(0).toUpperCase() + l.label.slice(1),
    value: l.value,
    color: ACCENT,
  })));

  // Tables per layer
  for (const layer of layers) {
    const layerElements = elements.filter((e) => e.layer === layer);
    if (layerElements.length === 0) continue;

    checkPageBreak(doc, 60);
    drawSectionTitle(doc, `${layer.charAt(0).toUpperCase() + layer.slice(1)} Layer (${layerElements.length})`);

    const rows = layerElements.map((e) => [
      e.name,
      e.type,
      e.status,
      e.riskLevel,
      `${e.maturity}/5`,
      e.domain,
    ]);
    drawTable(doc, ['Name', 'Type', 'Status', 'Risk', 'Maturity', 'Domain'],
      rows, [130, 95, 75, 60, 55, 80], 'Architecture Inventory');
  }
}

// ─── Roadmap Report ──────────────────────────────────────

async function renderRoadmapReport(doc: PDFKit.PDFDocument, project: { name: string }, roadmapId: string) {
  const roadmap = await TransformationRoadmap.findById(roadmapId).lean();
  if (!roadmap) throw new Error('Roadmap not found');

  const subtitle = `Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`;
  const strategyLabel = (roadmap.config as any)?.strategy || 'balanced';

  // Page 1: Executive Summary
  drawHeader(doc, `Transformation Roadmap — ${project.name}`, subtitle);
  drawFooter(doc, 1);

  drawSectionTitle(doc, 'Executive Summary');

  const summary = roadmap.summary as any || {};
  const costConfidence = summary.costConfidence || {};
  const metricY = doc.y;
  const cardW = (CONTENT_W - 10) / 2;

  drawMetricCard(doc, MARGIN, metricY, cardW, 'Total Cost (P50)',
    formatNumber(costConfidence.p50 || summary.totalCost || 0), '#f97316');
  drawMetricCard(doc, MARGIN + cardW + 10, metricY, cardW, 'Duration',
    `${summary.totalDurationMonths || 0} months`, '#3b82f6');
  drawMetricCard(doc, MARGIN, metricY + 60, cardW, 'Risk Reduction',
    `-${summary.riskReduction || 0}%`, '#22c55e');
  drawMetricCard(doc, MARGIN + cardW + 10, metricY + 60, cardW, 'Violations Fixed',
    `${summary.complianceImprovement || 0}`, '#a855f7');
  doc.y = metricY + 130;

  // Strategy & Config
  doc.font('Helvetica').fontSize(9).fillColor(DARK);
  doc.text(`Strategy: ${strategyLabel.charAt(0).toUpperCase() + strategyLabel.slice(1)}`, MARGIN, doc.y);
  doc.text(`Waves: ${summary.waveCount || 0}  |  Elements: ${summary.totalElements || 0}`, MARGIN, doc.y);
  if (costConfidence.p10 && costConfidence.p90) {
    doc.text(`Cost Range: ${formatNumber(costConfidence.p10)} (P10) — ${formatNumber(costConfidence.p90)} (P90)`, MARGIN, doc.y);
  }
  doc.moveDown();

  // Wave Summary Table
  const waves = (roadmap.waves as any[]) || [];
  if (waves.length > 0) {
    drawSectionTitle(doc, 'Wave Overview');
    const waveRows = waves.map((w: any) => [
      `Wave ${w.waveNumber}`,
      w.name || '-',
      `${w.elements?.length || 0}`,
      formatNumber(w.metrics?.totalCost || 0),
      `${w.estimatedDurationMonths || 0} mo`,
      `${(w.metrics?.riskDelta || 0) > 0 ? '+' : ''}${(w.metrics?.riskDelta || 0).toFixed(0)}%`,
    ]);
    drawTable(doc, ['Wave', 'Name', 'Elements', 'Cost', 'Duration', 'Risk Delta'],
      waveRows, [60, 140, 60, 80, 65, 90], 'Transformation Roadmap');
  }

  // Page 2+: Wave Details
  for (const wave of waves) {
    addNewPage(doc, `Transformation Roadmap — ${project.name}`, subtitle);
    drawSectionTitle(doc, `Wave ${wave.waveNumber}: ${wave.name || 'Unnamed'}`);

    if (wave.description) {
      doc.font('Helvetica').fontSize(9).fillColor(DARK).text(wave.description, MARGIN, doc.y, { width: CONTENT_W });
      doc.moveDown(0.5);
    }

    // Wave metrics
    const wMetrics = wave.metrics || {};
    const wMetricY = doc.y;
    const cardW3 = (CONTENT_W - 20) / 3;
    drawMetricCard(doc, MARGIN, wMetricY, cardW3, 'Cost', formatNumber(wMetrics.totalCost || 0));
    drawMetricCard(doc, MARGIN + cardW3 + 10, wMetricY, cardW3, 'Duration', `${wave.estimatedDurationMonths || 0} months`);
    drawMetricCard(doc, MARGIN + (cardW3 + 10) * 2, wMetricY, cardW3, 'Risk Delta',
      `${(wMetrics.riskDelta || 0) > 0 ? '+' : ''}${(wMetrics.riskDelta || 0).toFixed(0)}%`,
      (wMetrics.riskDelta || 0) < 0 ? '#22c55e' : '#ef4444');
    doc.y = wMetricY + 70;

    // Elements table
    const elements = wave.elements || [];
    if (elements.length > 0) {
      const elementRows = elements.map((el: any) => [
        el.name || '-',
        el.type || '-',
        `${el.currentStatus} → ${el.targetStatus}`,
        (el.riskScore || 0).toFixed(1),
        formatNumber(el.estimatedCost || 0),
      ]);
      drawTable(doc, ['Name', 'Type', 'Transition', 'Risk', 'Cost'],
        elementRows, [140, 90, 120, 50, 95], 'Transformation Roadmap');
    }

    // Recommendation
    if (wave.recommendation) {
      checkPageBreak(doc, 60);
      drawSectionTitle(doc, 'Recommendation');
      doc.font('Helvetica').fontSize(9).fillColor(DARK).text(wave.recommendation, MARGIN, doc.y, { width: CONTENT_W });
      doc.moveDown();
    }

    // Risk mitigations
    if (wave.riskMitigations && wave.riskMitigations.length > 0) {
      checkPageBreak(doc, 40);
      drawSectionTitle(doc, 'Risk Mitigations');
      for (const m of wave.riskMitigations) {
        doc.font('Helvetica').fontSize(9).fillColor(DARK).text(`• ${m}`, MARGIN + 10, doc.y, { width: CONTENT_W - 10 });
      }
      doc.moveDown();
    }
  }
}

// ─── Main Export ─────────────────────────────────────────

export type ReportType = 'executive' | 'simulation' | 'inventory' | 'roadmap';

export async function generateReport(
  projectId: string,
  type: ReportType,
  options?: { runId?: string; roadmapId?: string }
): Promise<PDFKit.PDFDocument> {
  const project = await Project.findById(projectId).lean();
  if (!project) throw new Error('Project not found');

  currentPage = 1;

  const doc = new PDFDocument({
    size: 'A4',
    margins: { top: 50, bottom: 50, left: 50, right: 50 },
    info: {
      Title: `TheArchitect — ${type.charAt(0).toUpperCase() + type.slice(1)} Report`,
      Author: 'TheArchitect',
      Subject: project.name,
    },
  });

  switch (type) {
    case 'executive':
      await renderExecutiveReport(doc, project, projectId);
      break;
    case 'simulation': {
      if (!options?.runId) throw new Error('runId is required for simulation reports');
      const run = await SimulationRun.findById(options.runId).lean();
      if (!run) throw new Error('Simulation run not found');
      await renderSimulationReport(doc, project, run as unknown as Record<string, unknown>);
      break;
    }
    case 'inventory':
      await renderInventoryReport(doc, project, projectId);
      break;
    case 'roadmap': {
      if (!options?.roadmapId) throw new Error('roadmapId is required for roadmap reports');
      await renderRoadmapReport(doc, project, options.roadmapId);
      break;
    }
    default:
      throw new Error(`Unknown report type: ${type}`);
  }

  doc.end();
  return doc;
}
