// ─── UC-GAP-001 (THE-307) ───────────────────────────────────────────────────
// Gap Analysis — answers the auditor question "what is still missing?".
// Three views on ComplianceRequirement (generated by UC-REQGEN-001):
//   A) per regulation — "5 of 9 open (56%)"
//   B) per element    — top elements with the most open MUST requirements
//   C) global KPIs + full open-items list + CSV export
// All numbers come live from GET /compliance/gaps on every load — never from
// cached pipeline stats (THE-389 design constraint).
import { useEffect, useMemo, useState, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { Target, Download, Wrench, Sparkles, CheckCircle2, Link2Off } from 'lucide-react';
import toast from 'react-hot-toast';
import { useComplianceStore } from '../../stores/complianceStore';
import { useArchitectureStore } from '../../stores/architectureStore';
import { architectureAPI } from '../../services/api';
import type { GapItem } from '../../services/api';
import { sortRequirementsForDisplay } from './RequirementsForElementSection';

const PRIORITY_BADGE: Record<GapItem['priority'], { label: string; bg: string; fg: string }> = {
  must:   { label: 'MUST',   bg: '#dc2626', fg: '#fff' },
  should: { label: 'SHOULD', bg: '#eab308', fg: '#0a0a0a' },
  may:    { label: 'MAY',    bg: '#3b82f6', fg: '#fff' },
};

const STATUS_OPTIONS: Array<{ value: GapItem['status']; label: string }> = [
  { value: 'open', label: 'Open' },
  { value: 'in_progress', label: 'In Progress' },
  { value: 'done', label: 'Done' },
  { value: 'waived', label: 'Waived' },
];

const STATUS_COLOR: Record<GapItem['status'], string> = {
  open: '#94a3b8',
  in_progress: '#3b82f6',
  done: '#22c55e',
  waived: '#64748b',
};

const OPEN_STATUSES = new Set<GapItem['status']>(['open', 'in_progress']);

function csvEscape(value: string): string {
  return /[",\n;]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

export function buildGapsCsv(items: GapItem[]): string {
  const header = 'Regulation,Requirement,Priority,Status,Age (days),Linked elements';
  const rows = items.map((g) =>
    [
      csvEscape(g.regulationTitle),
      csvEscape(g.title),
      g.priority,
      g.status,
      String(g.ageDays),
      String(g.linkedElementIds.length),
    ].join(','),
  );
  return [header, ...rows].join('\n');
}

export default function GapAnalysis() {
  const navigate = useNavigate();
  const { projectId } = useParams<{ projectId: string }>();
  const { gaps, gapsSummary, isLoadingGaps, loadGaps, updateGapStatus } = useComplianceStore();
  const elements = useArchitectureStore((s) => s.elements);

  const [regulationFilter, setRegulationFilter] = useState<string>('');
  const [priorityFilter, setPriorityFilter] = useState<'' | GapItem['priority']>('');
  const [savingId, setSavingId] = useState<string | null>(null);

  useEffect(() => {
    if (!projectId) return;
    void loadGaps(projectId, {
      regulationId: regulationFilter || undefined,
      priority: priorityFilter || undefined,
    });
  }, [projectId, regulationFilter, priorityFilter, loadGaps]);

  // The architecture store is only populated inside the project 3D view. When
  // the user lands on /compliance/gaps directly, fetch element names once so
  // "Top Gap Elements" shows names instead of raw ids.
  const [fetchedNames, setFetchedNames] = useState<Map<string, string>>(new Map());
  useEffect(() => {
    if (!projectId || elements.length > 0) return;
    let cancelled = false;
    architectureAPI
      .getElements(projectId)
      .then((res) => {
        if (cancelled) return;
        const list: Array<{ id: string; name: string }> = res.data?.data ?? [];
        setFetchedNames(new Map(list.map((el) => [el.id, el.name])));
      })
      .catch(() => {});
    return () => {
      cancelled = true;
    };
  }, [projectId, elements.length]);

  const elementNameById = useMemo(
    () => (elements.length > 0 ? new Map(elements.map((el) => [el.id, el.name])) : fetchedNames),
    [elements, fetchedNames],
  );

  const openItems = useMemo(
    () => sortRequirementsForDisplay(gaps.filter((g) => OPEN_STATUSES.has(g.status))),
    [gaps],
  );

  const handleStatusChange = useCallback(
    async (id: string, status: GapItem['status']) => {
      if (!projectId) return;
      setSavingId(id);
      const ok = await updateGapStatus(projectId, id, status);
      setSavingId(null);
      if (!ok) {
        toast.error('Status update failed');
        return;
      }
      // KPIs are only authoritative server-side — reload the aggregation.
      void loadGaps(projectId, {
        regulationId: regulationFilter || undefined,
        priority: priorityFilter || undefined,
      });
    },
    [projectId, updateGapStatus, loadGaps, regulationFilter, priorityFilter],
  );

  const handleExport = useCallback(() => {
    const csv = buildGapsCsv(openItems);
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'compliance-gaps.csv';
    a.click();
    URL.revokeObjectURL(url);
  }, [openItems]);

  const summary = gapsSummary;
  const totalOpen = summary ? summary.open + summary.inProgress : 0;
  const pctDone = summary && summary.total > 0
    ? Math.round(((summary.done + summary.waived) / summary.total) * 100)
    : 0;

  return (
    <div>
      {/* Header */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-lg bg-[#7c3aed]/20 flex items-center justify-center">
            <Target size={20} className="text-[#a78bfa]" />
          </div>
          <div>
            <h2 className="text-lg font-semibold text-white">Gap Analysis</h2>
            <p className="text-xs text-[var(--text-tertiary)]">
              Which requirements are still open — per regulation, per element, overall
            </p>
          </div>
        </div>
        {openItems.length > 0 && (
          <button
            onClick={handleExport}
            className="flex items-center gap-2 text-xs px-3 py-2 rounded-lg border border-[var(--border-subtle)] text-[var(--text-secondary)] hover:border-[#7c3aed]/40 hover:text-white transition"
          >
            <Download size={14} />
            Export CSV
          </button>
        )}
      </div>

      {isLoadingGaps && gaps.length === 0 && (
        <p className="text-sm text-[var(--text-tertiary)] py-8 text-center">Loading gap analysis…</p>
      )}

      {!isLoadingGaps && summary && summary.total === 0 && (
        <div className="text-center py-12">
          <Sparkles size={24} className="text-[var(--text-tertiary)] mx-auto mb-2" />
          <p className="text-sm text-[var(--text-secondary)]">No requirements generated yet.</p>
          <p className="text-xs text-[var(--text-tertiary)] mt-1">
            Generate requirements from a regulation first — the gap analysis tracks their fulfilment.
          </p>
        </div>
      )}

      {summary && summary.total > 0 && (
        <>
          {/* Global KPIs */}
          <div className="grid grid-cols-4 gap-3 mb-5" data-testid="gap-kpis">
            <div className="rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-raised)] p-3 text-center">
              <div className="text-xl font-bold" style={{ color: totalOpen > 0 ? '#ef4444' : '#22c55e' }}>{totalOpen}</div>
              <div className="text-[10px] text-[var(--text-tertiary)]">Open</div>
            </div>
            <div className="rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-raised)] p-3 text-center">
              <div className="text-xl font-bold text-[#dc2626]">{summary.openMust}</div>
              <div className="text-[10px] text-[var(--text-tertiary)]">Open MUST</div>
            </div>
            <div className="rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-raised)] p-3 text-center">
              <div className="text-xl font-bold text-[#22c55e]">{pctDone}%</div>
              <div className="text-[10px] text-[var(--text-tertiary)]">Resolved</div>
            </div>
            <div className="rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-raised)] p-3 text-center">
              <div className="text-xl font-bold text-[#eab308]">{summary.unlinked}</div>
              <div className="text-[10px] text-[var(--text-tertiary)]" title="Open requirements not linked to any element">Unlinked</div>
            </div>
          </div>

          {/* Filters */}
          <div className="flex items-center gap-2 mb-5">
            <select
              value={regulationFilter}
              onChange={(e) => setRegulationFilter(e.target.value)}
              aria-label="Filter by regulation"
              className="text-xs rounded border border-[var(--border-subtle)] bg-[var(--surface-raised)] px-2 py-1.5 text-[var(--text-secondary)] outline-none"
            >
              <option value="">All regulations</option>
              {summary.byRegulation.map((r) => (
                <option key={r.regulationId} value={r.regulationId}>{r.regulationTitle}</option>
              ))}
            </select>
            <select
              value={priorityFilter}
              onChange={(e) => setPriorityFilter(e.target.value as '' | GapItem['priority'])}
              aria-label="Filter by priority"
              className="text-xs rounded border border-[var(--border-subtle)] bg-[var(--surface-raised)] px-2 py-1.5 text-[var(--text-secondary)] outline-none"
            >
              <option value="">All priorities</option>
              <option value="must">MUST</option>
              <option value="should">SHOULD</option>
              <option value="may">MAY</option>
            </select>
          </div>

          {/* View A — per regulation */}
          <div className="mb-6">
            <h3 className="text-[10px] font-semibold uppercase tracking-wider text-[var(--text-tertiary)] mb-2">
              Per Regulation
            </h3>
            <div className="space-y-2">
              {summary.byRegulation.map((reg) => (
                <div
                  key={reg.regulationId}
                  className="rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-raised)] p-3"
                  data-testid={`gap-regulation-${reg.regulationId}`}
                >
                  <div className="flex items-center justify-between mb-1.5">
                    <span className="text-sm font-medium text-white">{reg.regulationTitle}</span>
                    <span className="text-xs text-[var(--text-secondary)]">
                      {reg.open} of {reg.total} open ({reg.pctOpen}%)
                      {reg.openMust > 0 && (
                        <span className="ml-2 text-[10px] font-bold text-[#dc2626]">{reg.openMust} MUST</span>
                      )}
                    </span>
                  </div>
                  <div className="h-1.5 rounded-full bg-[rgba(255,255,255,0.06)] overflow-hidden">
                    <div
                      className="h-full rounded-full bg-[#22c55e] transition-all"
                      style={{ width: `${100 - reg.pctOpen}%` }}
                    />
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* View C — top elements with open MUST requirements */}
          {summary.topElements.length > 0 && (
            <div className="mb-6">
              <h3 className="text-[10px] font-semibold uppercase tracking-wider text-[var(--text-tertiary)] mb-2">
                Top Gap Elements
              </h3>
              <div className="space-y-1">
                {summary.topElements.map((el) => (
                  <div
                    key={el.elementId}
                    className="flex items-center justify-between rounded border border-[var(--border-subtle)] bg-[var(--surface-raised)] px-3 py-2 text-xs"
                  >
                    <span className="text-[var(--text-secondary)] truncate">
                      {elementNameById.get(el.elementId) ?? el.elementId}
                    </span>
                    <span className="shrink-0 ml-3 text-[var(--text-tertiary)]">
                      {el.open} open
                      {el.openMust > 0 && (
                        <span className="ml-2 font-bold text-[#dc2626]">{el.openMust} MUST</span>
                      )}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Open items list */}
          <div className="mb-4">
            <h3 className="text-[10px] font-semibold uppercase tracking-wider text-[var(--text-tertiary)] mb-2">
              Open Requirements ({openItems.length})
            </h3>

            {openItems.length === 0 ? (
              <div className="text-center py-8" data-testid="gap-empty-state">
                <CheckCircle2 size={24} className="text-emerald-400 mx-auto mb-2" />
                <p className="text-sm text-emerald-400 font-medium">All requirements fulfilled — no gaps.</p>
              </div>
            ) : (
              <div className="space-y-2">
                {openItems.map((gap) => {
                  const badge = PRIORITY_BADGE[gap.priority];
                  return (
                    <div
                      key={gap._id}
                      className="rounded-lg border border-[var(--border-subtle)] bg-[var(--surface-raised)] p-3 space-y-1.5"
                    >
                      <div className="flex items-start gap-2">
                        <span
                          className="text-[8px] font-bold uppercase tracking-wider px-1 py-0.5 rounded shrink-0 mt-0.5"
                          style={{ backgroundColor: badge.bg, color: badge.fg }}
                        >
                          {badge.label}
                        </span>
                        <span className="text-sm font-medium text-white leading-snug flex-1">{gap.title}</span>
                        {gap.linkedElementIds.length === 0 && (
                          <span
                            className="flex items-center gap-1 text-[9px] text-[#eab308] shrink-0"
                            title="Not linked to any architecture element"
                          >
                            <Link2Off size={10} /> unlinked
                          </span>
                        )}
                      </div>
                      <p className="text-xs text-[var(--text-secondary)] leading-snug">{gap.description}</p>
                      <div className="flex items-center justify-between gap-2 pt-0.5">
                        <div className="flex items-center gap-3 text-[10px] text-[var(--text-tertiary)]">
                          <span>{gap.regulationTitle}</span>
                          <span>{gap.ageDays}d old</span>
                          <span>
                            {gap.linkedElementIds.length} element{gap.linkedElementIds.length === 1 ? '' : 's'}
                          </span>
                        </div>
                        <div className="flex items-center gap-2">
                          <select
                            value={gap.status}
                            onChange={(e) => handleStatusChange(gap._id, e.target.value as GapItem['status'])}
                            disabled={savingId === gap._id}
                            aria-label={`Status: ${gap.title}`}
                            className="text-[10px] rounded border border-[var(--border-subtle)] bg-[var(--surface-base)] px-1.5 py-0.5 outline-none cursor-pointer disabled:opacity-50"
                            style={{ color: STATUS_COLOR[gap.status] }}
                          >
                            {STATUS_OPTIONS.map((opt) => (
                              <option key={opt.value} value={opt.value}>{opt.label}</option>
                            ))}
                          </select>
                          <button
                            onClick={() => navigate(`/project/${projectId}/compliance/remediate`)}
                            title="Solve structurally: generate architecture elements with the Remediation Engine"
                            className="flex items-center gap-1 text-[10px] px-2 py-0.5 rounded border border-[#7c3aed]/30 text-[#a78bfa] hover:bg-[#7c3aed]/10 transition"
                          >
                            <Wrench size={10} />
                            Remediate
                          </button>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        </>
      )}
    </div>
  );
}
